import type { RuleCatalogEntry } from './types.ts';

export const MARKDOWNLINT_RULE_CATALOG: readonly RuleCatalogEntry[] = [
  {
    id: 'MD001',
    alias: 'heading-increment',
    aliases: ['heading-increment'],
    name: 'Heading levels should only increment by one level at a time',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md001.md',
    tags: ['headings'],
    options: [
      {
        key: 'front_matter_title',
        type: 'string',
        description: 'RegExp for matching title in front matter',
        default: '^\\s*title\\s*[:=]',
      },
    ],
  },
  {
    id: 'MD003',
    alias: 'heading-style',
    aliases: ['heading-style'],
    name: 'Heading style',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md003.md',
    tags: ['headings'],
    options: [
      {
        key: 'style',
        type: 'enum',
        description: 'Heading style',
        enum: [
          'consistent',
          'atx',
          'atx_closed',
          'setext',
          'setext_with_atx',
          'setext_with_atx_closed',
        ],
        default: 'consistent',
      },
    ],
  },
  {
    id: 'MD004',
    alias: 'ul-style',
    aliases: ['ul-style'],
    name: 'Unordered list style',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md004.md',
    tags: ['bullet', 'ul'],
    options: [
      {
        key: 'style',
        type: 'enum',
        description: 'List style',
        enum: ['consistent', 'asterisk', 'plus', 'dash', 'sublist'],
        default: 'consistent',
      },
    ],
  },
  {
    id: 'MD005',
    alias: 'list-indent',
    aliases: ['list-indent'],
    name: 'Inconsistent indentation for list items at the same level',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md005.md',
    tags: ['bullet', 'ul', 'indentation'],
    options: [],
  },
  {
    id: 'MD007',
    alias: 'ul-indent',
    aliases: ['ul-indent'],
    name: 'Unordered list indentation',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md007.md',
    tags: ['bullet', 'ul', 'indentation'],
    options: [
      { key: 'indent', type: 'integer', description: 'Spaces for indent', default: 2, minimum: 1 },
      {
        key: 'start_indented',
        type: 'boolean',
        description: 'Whether to indent the first level of the list',
        default: false,
      },
      {
        key: 'start_indent',
        type: 'integer',
        description: 'Spaces for first level indent (when start_indented is set)',
        default: 2,
        minimum: 1,
      },
    ],
  },
  {
    id: 'MD009',
    alias: 'no-trailing-spaces',
    aliases: ['no-trailing-spaces'],
    name: 'Trailing spaces',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md009.md',
    tags: ['whitespace'],
    options: [
      {
        key: 'br_spaces',
        type: 'integer',
        description: 'Spaces for line break',
        default: 2,
        minimum: 0,
      },
      { key: 'code_blocks', type: 'boolean', description: 'Include code blocks', default: false },
      {
        key: 'list_item_empty_lines',
        type: 'boolean',
        description: 'Allow spaces for empty lines in list items',
        default: false,
      },
      { key: 'strict', type: 'boolean', description: 'Include unnecessary breaks', default: false },
    ],
  },
  {
    id: 'MD010',
    alias: 'no-hard-tabs',
    aliases: ['no-hard-tabs'],
    name: 'Hard tabs',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md010.md',
    tags: ['whitespace', 'hard_tab'],
    options: [
      { key: 'code_blocks', type: 'boolean', description: 'Include code blocks', default: true },
      {
        key: 'ignore_code_languages',
        type: 'string-array',
        description: 'Fenced code languages to ignore',
        default: [],
      },
      {
        key: 'spaces_per_tab',
        type: 'integer',
        description: 'Number of spaces for each hard tab',
        default: 1,
        minimum: 0,
      },
    ],
  },
  {
    id: 'MD011',
    alias: 'no-reversed-links',
    aliases: ['no-reversed-links'],
    name: 'Reversed link syntax',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md011.md',
    tags: ['links'],
    options: [],
  },
  {
    id: 'MD012',
    alias: 'no-multiple-blanks',
    aliases: ['no-multiple-blanks'],
    name: 'Multiple consecutive blank lines',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md012.md',
    tags: ['whitespace', 'blank_lines'],
    options: [
      {
        key: 'maximum',
        type: 'integer',
        description: 'Consecutive blank lines',
        default: 1,
        minimum: 1,
      },
    ],
  },
  {
    id: 'MD013',
    alias: 'line-length',
    aliases: ['line-length'],
    name: 'Line length',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md013.md',
    tags: ['line_length'],
    options: [
      {
        key: 'line_length',
        type: 'integer',
        description: 'Number of characters',
        default: 80,
        minimum: 1,
      },
      {
        key: 'heading_line_length',
        type: 'integer',
        description: 'Number of characters for headings',
        default: 80,
        minimum: 1,
      },
      {
        key: 'code_block_line_length',
        type: 'integer',
        description: 'Number of characters for code blocks',
        default: 80,
        minimum: 1,
      },
      { key: 'code_blocks', type: 'boolean', description: 'Include code blocks', default: true },
      { key: 'tables', type: 'boolean', description: 'Include tables', default: true },
      { key: 'headings', type: 'boolean', description: 'Include headings', default: true },
      { key: 'strict', type: 'boolean', description: 'Strict length checking', default: false },
      { key: 'stern', type: 'boolean', description: 'Stern length checking', default: false },
    ],
  },
  {
    id: 'MD014',
    alias: 'commands-show-output',
    aliases: ['commands-show-output'],
    name: 'Dollar signs used before commands without showing output',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md014.md',
    tags: ['code'],
    options: [],
  },
  {
    id: 'MD018',
    alias: 'no-missing-space-atx',
    aliases: ['no-missing-space-atx'],
    name: 'No space after hash on atx style heading',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md018.md',
    tags: ['headings', 'atx', 'spaces'],
    options: [],
  },
  {
    id: 'MD019',
    alias: 'no-multiple-space-atx',
    aliases: ['no-multiple-space-atx'],
    name: 'Multiple spaces after hash on atx style heading',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md019.md',
    tags: ['headings', 'atx', 'spaces'],
    options: [],
  },
  {
    id: 'MD020',
    alias: 'no-missing-space-closed-atx',
    aliases: ['no-missing-space-closed-atx'],
    name: 'No space inside hashes on closed atx style heading',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md020.md',
    tags: ['headings', 'spaces', 'atx_closed'],
    options: [],
  },
  {
    id: 'MD021',
    alias: 'no-multiple-space-closed-atx',
    aliases: ['no-multiple-space-closed-atx'],
    name: 'Multiple spaces inside hashes on closed atx style heading',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md021.md',
    tags: ['headings', 'spaces', 'atx_closed'],
    options: [],
  },
  {
    id: 'MD022',
    alias: 'blanks-around-headings',
    aliases: ['blanks-around-headings'],
    name: 'Headings should be surrounded by blank lines',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md022.md',
    tags: ['headings', 'blank_lines'],
    options: [
      {
        key: 'include_front_matter',
        type: 'boolean',
        description: 'Include front matter content',
        default: false,
      },
      {
        key: 'lines_above',
        type: 'unsupported',
        description: 'Blank lines above heading',
        default: 1,
      },
      {
        key: 'lines_below',
        type: 'unsupported',
        description: 'Blank lines below heading',
        default: 1,
      },
    ],
  },
  {
    id: 'MD023',
    alias: 'heading-start-left',
    aliases: ['heading-start-left'],
    name: 'Headings must start at the beginning of the line',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md023.md',
    tags: ['headings', 'spaces'],
    options: [],
  },
  {
    id: 'MD024',
    alias: 'no-duplicate-heading',
    aliases: ['no-duplicate-heading'],
    name: 'Multiple headings with the same content',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md024.md',
    tags: ['headings'],
    options: [
      {
        key: 'siblings_only',
        type: 'boolean',
        description: 'Only check sibling headings',
        default: false,
      },
    ],
  },
  {
    id: 'MD025',
    alias: 'single-title',
    aliases: ['single-title', 'single-h1'],
    name: 'Multiple top-level headings in the same document',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md025.md',
    tags: ['headings'],
    options: [
      {
        key: 'front_matter_title',
        type: 'string',
        description: 'RegExp for matching title in front matter',
        default: '^\\s*title\\s*[:=]',
      },
      {
        key: 'level',
        type: 'integer',
        description: 'Heading level',
        default: 1,
        minimum: 1,
        maximum: 6,
      },
    ],
  },
  {
    id: 'MD026',
    alias: 'no-trailing-punctuation',
    aliases: ['no-trailing-punctuation'],
    name: 'Trailing punctuation in heading',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md026.md',
    tags: ['headings'],
    options: [
      {
        key: 'punctuation',
        type: 'string',
        description: 'Punctuation characters',
        default: '.,;:!。，；：！',
      },
    ],
  },
  {
    id: 'MD027',
    alias: 'no-multiple-space-blockquote',
    aliases: ['no-multiple-space-blockquote'],
    name: 'Multiple spaces after blockquote symbol',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md027.md',
    tags: ['indentation', 'whitespace', 'blockquote'],
    options: [
      { key: 'list_items', type: 'boolean', description: 'Include list items', default: true },
    ],
  },
  {
    id: 'MD028',
    alias: 'no-blanks-blockquote',
    aliases: ['no-blanks-blockquote'],
    name: 'Blank line inside blockquote',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md028.md',
    tags: ['whitespace', 'blockquote'],
    options: [],
  },
  {
    id: 'MD029',
    alias: 'ol-prefix',
    aliases: ['ol-prefix'],
    name: 'Ordered list item prefix',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md029.md',
    tags: ['ol'],
    options: [
      {
        key: 'style',
        type: 'enum',
        description: 'List style',
        enum: ['one', 'ordered', 'one_or_ordered', 'zero'],
        default: 'one_or_ordered',
      },
    ],
  },
  {
    id: 'MD030',
    alias: 'list-marker-space',
    aliases: ['list-marker-space'],
    name: 'Spaces after list markers',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md030.md',
    tags: ['ul', 'whitespace', 'ol'],
    options: [
      {
        key: 'ul_single',
        type: 'integer',
        description: 'Spaces for single-line unordered list items',
        default: 1,
        minimum: 1,
      },
      {
        key: 'ol_single',
        type: 'integer',
        description: 'Spaces for single-line ordered list items',
        default: 1,
        minimum: 1,
      },
      {
        key: 'ul_multi',
        type: 'integer',
        description: 'Spaces for multi-line unordered list items',
        default: 1,
        minimum: 1,
      },
      {
        key: 'ol_multi',
        type: 'integer',
        description: 'Spaces for multi-line ordered list items',
        default: 1,
        minimum: 1,
      },
    ],
  },
  {
    id: 'MD031',
    alias: 'blanks-around-fences',
    aliases: ['blanks-around-fences'],
    name: 'Fenced code blocks should be surrounded by blank lines',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md031.md',
    tags: ['blank_lines', 'code'],
    options: [
      { key: 'list_items', type: 'boolean', description: 'Include list items', default: true },
    ],
  },
  {
    id: 'MD032',
    alias: 'blanks-around-lists',
    aliases: ['blanks-around-lists'],
    name: 'Lists should be surrounded by blank lines',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md032.md',
    tags: ['bullet', 'ul', 'blank_lines', 'ol'],
    options: [],
  },
  {
    id: 'MD033',
    alias: 'no-inline-html',
    aliases: ['no-inline-html'],
    name: 'Inline HTML',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md033.md',
    tags: ['html'],
    options: [
      {
        key: 'allowed_elements',
        type: 'string-array',
        description: 'Allowed elements',
        default: [],
      },
      {
        key: 'table_allowed_elements',
        type: 'string-array',
        description: 'Allowed elements in tables',
        default: [],
      },
    ],
  },
  {
    id: 'MD034',
    alias: 'no-bare-urls',
    aliases: ['no-bare-urls'],
    name: 'Bare URL used',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md034.md',
    tags: ['links', 'url'],
    options: [],
  },
  {
    id: 'MD035',
    alias: 'hr-style',
    aliases: ['hr-style'],
    name: 'Horizontal rule style',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md035.md',
    tags: ['hr'],
    options: [
      { key: 'style', type: 'string', description: 'Horizontal rule style', default: 'consistent' },
    ],
  },
  {
    id: 'MD036',
    alias: 'no-emphasis-as-heading',
    aliases: ['no-emphasis-as-heading'],
    name: 'Emphasis used instead of a heading',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md036.md',
    tags: ['headings', 'emphasis'],
    options: [
      {
        key: 'punctuation',
        type: 'string',
        description: 'Punctuation characters',
        default: '.,;:!?。，；：！？',
      },
    ],
  },
  {
    id: 'MD037',
    alias: 'no-space-in-emphasis',
    aliases: ['no-space-in-emphasis'],
    name: 'Spaces inside emphasis markers',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md037.md',
    tags: ['whitespace', 'emphasis'],
    options: [],
  },
  {
    id: 'MD038',
    alias: 'no-space-in-code',
    aliases: ['no-space-in-code'],
    name: 'Spaces inside code span elements',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md038.md',
    tags: ['whitespace', 'code'],
    options: [],
  },
  {
    id: 'MD039',
    alias: 'no-space-in-links',
    aliases: ['no-space-in-links'],
    name: 'Spaces inside link text',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md039.md',
    tags: ['whitespace', 'links'],
    options: [],
  },
  {
    id: 'MD040',
    alias: 'fenced-code-language',
    aliases: ['fenced-code-language'],
    name: 'Fenced code blocks should have a language specified',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md040.md',
    tags: ['code', 'language'],
    options: [
      {
        key: 'allowed_languages',
        type: 'string-array',
        description: 'List of languages',
        default: [],
      },
      {
        key: 'language_only',
        type: 'boolean',
        description: 'Require language only',
        default: false,
      },
    ],
  },
  {
    id: 'MD041',
    alias: 'first-line-heading',
    aliases: ['first-line-heading', 'first-line-h1'],
    name: 'First line in a file should be a top-level heading',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md041.md',
    tags: ['headings'],
    options: [
      {
        key: 'allow_preamble',
        type: 'boolean',
        description: 'Allow content before first heading',
        default: false,
      },
      {
        key: 'front_matter_title',
        type: 'string',
        description: 'RegExp for matching title in front matter',
        default: '^\\s*title\\s*[:=]',
      },
      {
        key: 'level',
        type: 'integer',
        description: 'Heading level',
        default: 1,
        minimum: 1,
        maximum: 6,
      },
    ],
  },
  {
    id: 'MD042',
    alias: 'no-empty-links',
    aliases: ['no-empty-links'],
    name: 'No empty links',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md042.md',
    tags: ['links'],
    options: [],
  },
  {
    id: 'MD043',
    alias: 'required-headings',
    aliases: ['required-headings'],
    name: 'Required heading structure',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md043.md',
    tags: ['headings'],
    options: [
      { key: 'headings', type: 'string-array', description: 'List of headings', default: [] },
      { key: 'match_case', type: 'boolean', description: 'Match case of headings', default: false },
    ],
  },
  {
    id: 'MD044',
    alias: 'proper-names',
    aliases: ['proper-names'],
    name: 'Proper names should have the correct capitalization',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md044.md',
    tags: ['spelling'],
    options: [
      { key: 'names', type: 'string-array', description: 'List of proper names', default: [] },
      { key: 'code_blocks', type: 'boolean', description: 'Include code blocks', default: true },
      {
        key: 'html_elements',
        type: 'boolean',
        description: 'Include HTML elements',
        default: true,
      },
    ],
  },
  {
    id: 'MD045',
    alias: 'no-alt-text',
    aliases: ['no-alt-text'],
    name: 'Images should have alternate text (alt text)',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md045.md',
    tags: ['accessibility', 'images'],
    options: [],
  },
  {
    id: 'MD046',
    alias: 'code-block-style',
    aliases: ['code-block-style'],
    name: 'Code block style',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md046.md',
    tags: ['code'],
    options: [
      {
        key: 'style',
        type: 'enum',
        description: 'Block style',
        enum: ['consistent', 'fenced', 'indented'],
        default: 'consistent',
      },
    ],
  },
  {
    id: 'MD047',
    alias: 'single-trailing-newline',
    aliases: ['single-trailing-newline'],
    name: 'Files should end with a single newline character',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md047.md',
    tags: ['blank_lines'],
    options: [],
  },
  {
    id: 'MD048',
    alias: 'code-fence-style',
    aliases: ['code-fence-style'],
    name: 'Code fence style',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md048.md',
    tags: ['code'],
    options: [
      {
        key: 'style',
        type: 'enum',
        description: 'Code fence style',
        enum: ['consistent', 'backtick', 'tilde'],
        default: 'consistent',
      },
    ],
  },
  {
    id: 'MD049',
    alias: 'emphasis-style',
    aliases: ['emphasis-style'],
    name: 'Emphasis style',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md049.md',
    tags: ['emphasis'],
    options: [
      {
        key: 'style',
        type: 'enum',
        description: 'Emphasis style',
        enum: ['consistent', 'asterisk', 'underscore'],
        default: 'consistent',
      },
    ],
  },
  {
    id: 'MD050',
    alias: 'strong-style',
    aliases: ['strong-style'],
    name: 'Strong style',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md050.md',
    tags: ['emphasis'],
    options: [
      {
        key: 'style',
        type: 'enum',
        description: 'Strong style',
        enum: ['consistent', 'asterisk', 'underscore'],
        default: 'consistent',
      },
    ],
  },
  {
    id: 'MD051',
    alias: 'link-fragments',
    aliases: ['link-fragments'],
    name: 'Link fragments should be valid',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md051.md',
    tags: ['links'],
    options: [
      {
        key: 'ignore_case',
        type: 'boolean',
        description: 'Ignore case of fragments',
        default: false,
      },
      {
        key: 'ignored_pattern',
        type: 'string',
        description: 'Pattern for ignoring additional fragments',
        default: '',
      },
    ],
  },
  {
    id: 'MD052',
    alias: 'reference-links-images',
    aliases: ['reference-links-images'],
    name: 'Reference links and images should use a label that is defined',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md052.md',
    tags: ['links', 'images'],
    options: [
      {
        key: 'ignored_labels',
        type: 'string-array',
        description: 'Ignored link labels',
        default: ['x'],
      },
      {
        key: 'shortcut_syntax',
        type: 'boolean',
        description: 'Include shortcut syntax',
        default: false,
      },
    ],
  },
  {
    id: 'MD053',
    alias: 'link-image-reference-definitions',
    aliases: ['link-image-reference-definitions'],
    name: 'Link and image reference definitions should be needed',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md053.md',
    tags: ['links', 'images'],
    options: [
      {
        key: 'ignored_definitions',
        type: 'string-array',
        description: 'Ignored definitions',
        default: ['//'],
      },
    ],
  },
  {
    id: 'MD054',
    alias: 'link-image-style',
    aliases: ['link-image-style'],
    name: 'Link and image style',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md054.md',
    tags: ['links', 'images'],
    options: [
      { key: 'autolink', type: 'boolean', description: 'Allow autolinks', default: true },
      {
        key: 'inline',
        type: 'boolean',
        description: 'Allow inline links and images',
        default: true,
      },
      {
        key: 'full',
        type: 'boolean',
        description: 'Allow full reference links and images',
        default: true,
      },
      {
        key: 'collapsed',
        type: 'boolean',
        description: 'Allow collapsed reference links and images',
        default: true,
      },
      {
        key: 'shortcut',
        type: 'boolean',
        description: 'Allow shortcut reference links and images',
        default: true,
      },
      {
        key: 'url_inline',
        type: 'boolean',
        description: 'Allow URLs as inline links',
        default: true,
      },
    ],
  },
  {
    id: 'MD055',
    alias: 'table-pipe-style',
    aliases: ['table-pipe-style'],
    name: 'Table pipe style',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md055.md',
    tags: ['table'],
    options: [
      {
        key: 'style',
        type: 'enum',
        description: 'Table pipe style',
        enum: [
          'consistent',
          'leading_only',
          'trailing_only',
          'leading_and_trailing',
          'no_leading_or_trailing',
        ],
        default: 'consistent',
      },
    ],
  },
  {
    id: 'MD056',
    alias: 'table-column-count',
    aliases: ['table-column-count'],
    name: 'Table column count',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md056.md',
    tags: ['table'],
    options: [],
  },
  {
    id: 'MD058',
    alias: 'blanks-around-tables',
    aliases: ['blanks-around-tables'],
    name: 'Tables should be surrounded by blank lines',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md058.md',
    tags: ['table'],
    options: [],
  },
  {
    id: 'MD059',
    alias: 'descriptive-link-text',
    aliases: ['descriptive-link-text'],
    name: 'Link text should be descriptive',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md059.md',
    tags: ['links', 'accessibility'],
    options: [
      {
        key: 'prohibited_texts',
        type: 'string-array',
        description: 'Prohibited link texts',
        default: ['click here', 'here', 'link', 'more'],
      },
    ],
  },
  {
    id: 'MD060',
    alias: 'table-column-style',
    aliases: ['table-column-style'],
    name: 'Table column style',
    docUrl: 'https://github.com/DavidAnson/markdownlint/blob/v0.41.1/doc/md060.md',
    tags: ['table'],
    options: [
      {
        key: 'style',
        type: 'enum',
        description: 'Table column style',
        enum: ['any', 'aligned', 'compact', 'tight'],
        default: 'any',
      },
      {
        key: 'aligned_delimiter',
        type: 'boolean',
        description: 'Aligned delimiter columns',
        default: false,
      },
    ],
  },
];
