// Users Three — Phosphor `UsersThree`, FILL weight, 256 viewBox.
//
// THE GESTURE (Bakai): the three rotate one place clockwise. The person in front
// goes back, and the next one comes forward. It completes FORWARD and never
// undoes — one step lands on the resting picture because each slot receives a
// figure that has morphed into that slot's own shape.
//
// ── WHAT THE SOURCE ACTUALLY IS ──────────────────────────────────────────────
// Every structural arc, recovered by endpoint -> centre parameterisation:
//   LEFT    head r40.000 @ ( 63.950,87.952)  shoulders r67.790 @ ( 63.947,179.714)
//   RIGHT   head r40.000 @ (192.050,87.952)  shoulders r67.760 @ (191.995,179.656)
//   CENTRE  head r48.000 @ (127.935,143.962) shoulders r72.130 @ (127.427,248.255)
//                                                  and r72.150 @ (128.580,248.305)
//   the two CUTS in the side figures: r64.080 @ (128.080,144.055),(127.920,144.055)
//
// THE CUT IS A DILATION, AND THAT IS THE WHOLE UNLOCK. Both cut arcs are
// concentric with the CENTRE head and 64.08 - 48 = 16.08 outside it. 16 is this
// icon's own line weight. So Phosphor's white channel is the front person's
// silhouette dilated by one line width — which means it can be REGENERATED for
// any arrangement instead of being baked into the artwork. Without that the three
// figures are welded to one pose and no rotation is possible at all.
//
// SO THE FIGURES ARE REBUILT UNCUT: head circle union body, each SYMMETRIC ABOUT
// ITS OWN AXIS, authored in local coordinates with the head centre at the
// origin. Back-left and back-right therefore become the same shape at a
// different x, and travelling between them is a pure translate with no mirror.
// The union is exact by construction — the shoulder arc peaks exactly 16u above
// the head circle's bottom, so the two overlap by the line weight and no butted
// edge exists to hairline (fill weight, same colour).
//
// The FRONT body closes across the top on the chord y=182.07, x 98.82 -> 157.19,
// and the head r48 crosses y=182.07 at x 98.735/157.135 — so that closure lies on
// the head's own boundary to within 0.06u and is buried inside it. Measured, not
// fudged. Same for BACK: its shoulder arc meets the head circle at (+/-26.947,
// 29.558) local, which is the source's own (37,117.51) point exactly.
//
// Rest measures 157 px >8 at max 62 against the untouched source at 40px@2x. That
// max is the 2a(1-a) split-path signature (one path became six elements; 25% of
// 255 = 64), not geometry. The only true deltas are the four r3.94/r4 fillets
// Phosphor hand-drew where its cut meets each figure; a regenerated cut makes
// those corners sharp. They are ~0.6u, about 0.1px at ship size, and they are the
// unavoidable price of a cut that has to move. Stated, not buried.
//
// ── DEPTH, AND WHY THE MASK HANDOFF IS FREE ──────────────────────────────────
// Over the step: A goes FRONT -> BACK-LEFT (near -> far), C goes BACK-RIGHT ->
// FRONT (far -> near), B crosses the back left -> right and is far throughout.
// So B is always behind both, and A and C swap rank exactly once, at 50%.
//
// That swap is free, and the ring is what makes it free. At 50% A and C sit at
// the two BACK slots, x63.8 and x192.1; at that depth each is about 121 wide, so
// they span 3.2..124.4 and 131.5..252.6 — a 9.6u gap, and they cannot touch. The
// rank swap therefore happens at a provably covered instant, so the mask handoff
// is a hard flip on a hundredth of a percent rather than anything blended.
//
// Masks, in full: A is cut by C (gated ON from 50%); C is cut by A (gated ON
// until 50%); B is cut by both, always. A is never behind B and C is never behind
// B, so those pairs need nothing. At 100% the roles have swapped and the picture
// is the resting picture again with different elements playing each part, so when
// the driver clears data-go and everything snaps back, nothing visibly moves.
// That is the Kanban congruence trick applied to depth instead of to position.
//
// The body morph is 8 cubics per pose, generated by converting both outlines to
// cubics with matching structure (BACK's double corner arc against FRONT's single
// one, split to match). Every coordinate is the source's own digit or a de
// Casteljau product of one. Transforms, `r` and `d` only. No opacity anywhere.

import { useId } from "react";

type P = { size?: number; className?: string };
type Track = "a" | "b" | "c";

/* Local coords: head centre at the origin, so a figure is position-independent. */
const BODY_BACK =
    "M-26.947,29.558C-37.704,34.218 -47.069,41.588 -54.127,50.948C-53.606,53.384 -54.2,55.925 -55.747,57.878C-54.897,61.497 -51.665,64.054 -47.947,64.048C-15.982,64.048 15.982,64.048 47.947,64.048C48.797,60.429 52.029,57.872 55.747,57.878C56.268,55.442 55.674,52.901 54.127,50.948C47.069,41.588 37.704,34.218 26.947,29.558C8.982,29.558 -8.982,29.558 -26.947,29.558Z";
const BODY_FRONT =
    "M-29.115,38.108C-43.286,44.203 -55.111,54.702 -62.864,68.038C-64.294,70.513 -64.294,73.563 -62.865,76.039C-61.435,78.514 -58.793,80.039 -55.935,80.038C-18.602,80.038 18.732,80.038 56.065,80.038C58.923,80.039 61.565,78.514 62.995,76.039C64.424,73.563 64.424,70.513 62.995,68.038C55.236,54.712 43.411,44.223 29.255,38.108C9.798,38.108 -9.658,38.108 -29.115,38.108Z";

/* 2 x (64.08 - 48): the channel Phosphor draws, restated as a dilation. */
const GAP2 = 32.16;

/* rest: A in front, B back-left, C back-right — the source's own arrangement */
const REST: Record<Track, { r: number; d: string }> = {
    a: { r: 48, d: BODY_FRONT },
    b: { r: 40, d: BODY_BACK },
    c: { r: 40, d: BODY_BACK },
};

function Figure({ t, sil, converted }: { t: Track; sil?: boolean; converted?: boolean }) {
    const R = REST[t];
    const outlineMask = `u3-outline-${useId().replace(/[^a-zA-Z0-9]/g, "")}`;
    const geometry = () => (
        <>
            <circle className={`u3-${t}-h`} cx={0} cy={0} r={R.r} />
            <path className={`u3-${t}-b`} d={R.d} />
        </>
    );
    return (
        <g
            className={`u3-${t}`}
            {...(sil ? { fill: "#000", stroke: "#000", strokeWidth: GAP2, strokeLinejoin: "round" } : {})}
        >
            {converted && !sil ? (
                <>
                    <defs>
                        {/* Build only the OUTSIDE of the head/body union. A 32u
                            white stroke followed by the solid union in black
                            removes the inner half and every overlap seam, leaving
                            one transparent figure with a consistent 16u contour. */}
                        <mask id={outlineMask} maskUnits="userSpaceOnUse" x="-96" y="-96" width="192" height="256">
                            <rect x="-96" y="-96" width="192" height="256" fill="#000" />
                            <g fill="none" stroke="#fff" strokeWidth="32" strokeLinejoin="round">
                                {geometry()}
                            </g>
                            <g fill="#000">{geometry()}</g>
                        </mask>
                    </defs>
                    <rect x="-96" y="-96" width="192" height="256" fill="var(--converted-ink)" mask={`url(#${outlineMask})`} />
                </>
            ) : geometry()}
        </g>
    );
}

export function UsersThreeLive({ size = 16, className, converted }: P & { converted?: boolean }) {
    const uid = useId().replace(/[^a-zA-Z0-9]/g, "");
    const mA = `u3a-${uid}`;
    const mB = `u3b-${uid}`;
    const mC = `u3c-${uid}`;
    const box = { x: "-96", y: "-96", width: "448", height: "448" } as const;
    return (
        <svg width={size} height={size} viewBox="0 0 256 256" fill="currentColor" className={className}>
            <defs>
                {/* A is cut by C, but only once C is the nearer of the two */}
                <mask id={mA} maskUnits="userSpaceOnUse" {...box}>
                    <rect {...box} fill="#fff" />
                    <g className="u3-gate-c">
                        <Figure t="c" sil />
                    </g>
                </mask>
                {/* B is behind both for the whole step */}
                <mask id={mB} maskUnits="userSpaceOnUse" {...box}>
                    <rect {...box} fill="#fff" />
                    <Figure t="a" sil />
                    <Figure t="c" sil />
                </mask>
                {/* C is cut by A until A falls behind it */}
                <mask id={mC} maskUnits="userSpaceOnUse" {...box}>
                    <rect {...box} fill="#fff" />
                    <g className="u3-gate-a">
                        <Figure t="a" sil />
                    </g>
                </mask>
            </defs>

            <g mask={`url(#${mB})`}>
                <Figure t="b" converted={converted} />
            </g>
            <g mask={`url(#${mA})`}>
                <Figure t="a" converted={converted} />
            </g>
            <g mask={`url(#${mC})`}>
                <Figure t="c" converted={converted} />
            </g>
        </svg>
    );
}
