// Users Three — Phosphor `UsersThree`, FILL weight, 256 viewBox.
//
// THE GESTURE (Bakai): the three rotate one place clockwise. The person in front
// goes back, and the next one comes forward. It completes FORWARD and never
// undoes — one step lands on the resting picture because each slot receives a
// figure that has morphed into that slot's own shape.
//
// ── WHAT THE SOURCE ACTUALLY IS ──────────────────────────────────────────────
// Every structural arc, recovered by endpoint -> centre parameterisation:
//   LEFT    head r40.000 @ ( 63.950,87.952)  shoulders r67.790 @ ( 63.947,179.714)
//   RIGHT   head r40.000 @ (192.050,87.952)  shoulders r67.760 @ (191.995,179.656)
//   CENTRE  head r48.000 @ (127.935,143.962) shoulders r72.130 @ (127.427,248.255)
//                                                  and r72.150 @ (128.580,248.305)
//   the two CUTS in the side figures: r64.080 @ (128.080,144.055),(127.920,144.055)
//
// THE CUT IS A DILATION, AND THAT IS THE WHOLE UNLOCK. Both cut arcs are
// concentric with the CENTRE head and 64.08 - 48 = 16.08 outside it. 16 is this
// icon's own line weight. So Phosphor's white channel is the front person's
// silhouette dilated by one line width — which means it can be REGENERATED for
// any arrangement instead of being baked into the artwork. Without that the three
// figures are welded to one pose and no rotation is possible at all.
//
// SO THE FIGURES ARE REBUILT UNCUT: head circle union body, each SYMMETRIC ABOUT
// ITS OWN AXIS, authored in local coordinates with the head centre at the
// origin. Back-left and back-right therefore become the same shape at a
// different x, and travelling between them is a pure translate with no mirror.
// The union is exact by construction — the shoulder arc peaks exactly 16u above
// the head circle's bottom, so the two overlap by the line weight and no butted
// edge exists to hairline (fill weight, same colour).
//
// The FRONT body closes across the top on the chord y=182.07, x 98.82 -> 157.19,
// and the head r48 crosses y=182.07 at x 98.735/157.135 — so that closure lies on
// the head's own boundary to within 0.06u and is buried inside it. Measured, not
// fudged. Same for BACK: its shoulder arc meets the head circle at (+/-26.947,
// 29.558) local, which is the source's own (37,117.51) point exactly.
//
// Rest measures 157 px >8 at max 62 against the untouched source at 40px@2x. That
// max is the 2a(1-a) split-path signature (one path became six elements; 25% of
// 255 = 64), not geometry. The only true deltas are the four r3.94/r4 fillets
// Phosphor hand-drew where its cut meets each figure; a regenerated cut makes
// those corners sharp. They are ~0.6u, about 0.1px at ship size, and they are the
// unavoidable price of a cut that has to move. Stated, not buried.
//
// ── DEPTH, AND WHY THE MASK HANDOFF IS FREE ──────────────────────────────────
// Over the step: A goes FRONT -> BACK-LEFT (near -> far), C goes BACK-RIGHT ->
// FRONT (far -> near), B crosses the back left -> right and is far throughout.
// So B is always behind both, and A and C swap rank exactly once, at 50%.
//
// That swap is free, and the ring is what makes it free. At 50% A and C sit at
// the two BACK slots, x63.8 and x192.1; at that depth each is about 121 wide, so
// they span 3.2..124.4 and 131.5..252.6 — a 9.6u gap, and they cannot touch. The
// rank swap therefore happens at a provably covered instant, so the mask handoff
// is a hard flip on a hundredth of a percent rather than anything blended.
//
// Masks, in full: A is cut by C (gated ON from 50%); C is cut by A (gated ON
// until 50%); B is cut by both, always. A is never behind B and C is never behind
// B, so those pairs need nothing. At 100% the roles have swapped and the picture
// is the resting picture again with different elements playing each part, so when
// the driver clears data-go and everything snaps back, nothing visibly moves.
// That is the Kanban congruence trick applied to depth instead of to position.
//
// The body morph is 8 cubics per pose, generated by converting both outlines to
// cubics with matching structure (BACK's double corner arc against FRONT's single
// one, split to match). Every coordinate is the source's own digit or a de
// Casteljau product of one. Transforms, `r` and `d` only. No opacity anywhere.

import { useId } from "react";

type P = { size?: number; className?: string };
type Track = "a" | "b" | "c";

/* Local coords: head centre at the origin, so a figure is position-independent. */
const BODY_BACK =
    "M-26.947,29.558C-37.704,34.218 -47.069,41.588 -54.127,50.948C-53.606,53.384 -54.2,55.925 -55.747,57.878C-54.897,61.497 -51.665,64.054 -47.947,64.048C-15.982,64.048 15.982,64.048 47.947,64.048C48.797,60.429 52.029,57.872 55.747,57.878C56.268,55.442 55.674,52.901 54.127,50.948C47.069,41.588 37.704,34.218 26.947,29.558C8.982,29.558 -8.982,29.558 -26.947,29.558Z";
const BODY_FRONT =
    "M-29.115,38.108C-43.286,44.203 -55.111,54.702 -62.864,68.038C-64.294,70.513 -64.294,73.563 -62.865,76.039C-61.435,78.514 -58.793,80.039 -55.935,80.038C-18.602,80.038 18.732,80.038 56.065,80.038C58.923,80.039 61.565,78.514 62.995,76.039C64.424,73.563 64.424,70.513 62.995,68.038C55.236,54.712 43.411,44.223 29.255,38.108C9.798,38.108 -9.658,38.108 -29.115,38.108Z";

/* 2 x (64.08 - 48): the channel Phosphor draws, restated as a dilation. */
const GAP2 = 32.16;

/* rest: A in front, B back-left, C back-right — the source's own arrangement */
const REST: Record<Track, { r: number; d: string }> = {
    a: { r: 48, d: BODY_FRONT },
    b: { r: 40, d: BODY_BACK },
    c: { r: 40, d: BODY_BACK },
};

function Figure({ t, sil, converted }: { t: Track; sil?: boolean; converted?: boolean }) {
    const R = REST[t];
    const outlineMask = `u3-outline-${useId().replace(/[^a-zA-Z0-9]/g, "")}`;
    const geometry = () => (
        <>
            <circle className={`u3-${t}-h`} cx={0} cy={0} r={R.r} />
            <path className={`u3-${t}-b`} d={R.d} />
        </>
    );
    return (
        <g
            className={`u3-${t}`}
            {...(sil ? { fill: "#000", stroke: "#000", strokeWidth: GAP2, strokeLinejoin: "round" } : {})}
        >
            {converted && !sil ? (
                <>
                    <defs>
                        {/* Build only the OUTSIDE of the head/body union. A 32u
                            white stroke followed by the solid union in black
                            removes the inner half and every overlap seam, leaving
                            one transparent figure with a consistent 16u contour. */}
                        <mask id={outlineMask} maskUnits="userSpaceOnUse" x="-96" y="-96" width="192" height="256">
                            <rect x="-96" y="-96" width="192" height="256" fill="#000" />
                            <g fill="none" stroke="#fff" strokeWidth="32" strokeLinejoin="round">
                                {geometry()}
                            </g>
                            <g fill="#000">{geometry()}</g>
                        </mask>
                    </defs>
                    <rect x="-96" y="-96" width="192" height="256" fill="var(--converted-ink)" mask={`url(#${outlineMask})`} />
                </>
            ) : geometry()}
        </g>
    );
}

export function UsersThreeLive({ size = 16, className, converted }: P & { converted?: boolean }) {
    const uid = useId().replace(/[^a-zA-Z0-9]/g, "");
    const mA = `u3a-${uid}`;
    const mB = `u3b-${uid}`;
    const mC = `u3c-${uid}`;
    const box = { x: "-96", y: "-96", width: "448", height: "448" } as const;
    return (
        <svg width={size} height={size} viewBox="0 0 256 256" fill="currentColor" className={className}>
            <defs>
                {/* A is cut by C, but only once C is the nearer of the two */}
                <mask id={mA} maskUnits="userSpaceOnUse" {...box}>
                    <rect {...box} fill="#fff" />
                    <g className="u3-gate-c">
                        <Figure t="c" sil />
                    </g>
                </mask>
                {/* B is behind both for the whole step */}
                <mask id={mB} maskUnits="userSpaceOnUse" {...box}>
                    <rect {...box} fill="#fff" />
                    <Figure t="a" sil />
                    <Figure t="c" sil />
                </mask>
                {/* C is cut by A until A falls behind it */}
                <mask id={mC} maskUnits="userSpaceOnUse" {...box}>
                    <rect {...box} fill="#fff" />
                    <g className="u3-gate-a">
                        <Figure t="a" sil />
                    </g>
                </mask>
            </defs>

            <g mask={`url(#${mB})`}>
                <Figure t="b" converted={converted} />
            </g>
            <g mask={`url(#${mA})`}>
                <Figure t="a" converted={converted} />
            </g>
            <g mask={`url(#${mC})`}>
                <Figure t="c" converted={converted} />
            </g>
        </svg>
    );
}

export const USERSTHREE_CSS = `
.lg-u3 .u3-a { transform: translate(127.935px,143.962px); }
.lg-u3 .u3-b { transform: translate(63.947px,87.952px); }
.lg-u3 .u3-c { transform: translate(192.053px,87.952px); }
.lg-u3 .u3-gate-c { visibility: hidden; }
.lg-u3 .u3-gate-a { visibility: visible; }

/* ── THE TURNTABLE ────────────────────────────────────────────────────────────
   The first build hand-picked three bowed paths and the composition visibly
   narrowed and wobbled (the group's ink collapsed from 112px to 95px mid
   gesture). Replaced with a real ring, SOLVED from the three resting slots:

     x = 127.935 + 74.04*sin(t)      127.935 + 74.04*sin(120) = 192.053
     y = 106.620 + 37.34*cos(t)      CY - RY = 143.962 ; CY + RY/2 = 87.952
     shape u = clamp((cos t + 0.5)/1.5, 0, 1)      1 at the front, 0 at the back

   All three sit at t, t-120, t-240 and sweep 120 deg together, so at every
   instant the arrangement is the resting arrangement rotated, and the group's
   width now holds at 232-249 instead of collapsing.

   Sampled at 9 points with the ease baked into the SAMPLE TIMES and joined
   linearly (the Address Book trick: sampling a real curve beats guessing a
   bezier). That ease is cubic-bezier(0.08,0.12,0.85,0.95).

   THREE CURVES, and the middle one was a bug of its own. The first pass used
   (0.45,0,0.55,1): start slope ZERO, ease-in in all but name, which VERIFY.md
   names as the tell for a gesture that reads sluggish. Bakai called it. The fix
   over-corrected to (0.22,0.55,0.28,1), start slope 2.5 — but that curve does
   HALF THE TRAVEL IN THE FIRST 19.5% of the clock and crawls the rest out over
   the remaining 579ms, so it lurched and then drifted. Bakai called that too.
   The two requirements pull against each other and have to be solved together:
   a real start slope needs y1/x1 up, while keeping half-travel near mid-clock
   needs x2 pushed right. (0.08,0.12,0.85,0.95) gets start slope 1.50, end slope
   0.33, and half-travel at 44.84%. The endpoint keyframes are pinned to the measured slots so rest is
   exact rather than 0.13u off. And x is CLAMPED to the figure's own half-width
   from each edge, because the svg clips at the viewBox: the ring flattens by
   about 8u between the slots rather than carrying a body's outer edge onto
   the frame edge.

   THAT CLAMP WAS ITSELF A BUG and Bakai caught it: it PINNED figure A against
   the edge for 327ms of 720, and C for 130ms — 457ms of dead flat spot between
   the three, which reads as the sides hitching. Replaced with a third harmonic,
   x = CX + RX*(sin t + 0.18*sin 3t). sin(3t) is zero at every multiple of 60
   degrees, so all three slots AND the +/-60 depth crossing keep their exact
   solved values and only the bulge between them is pulled in. Peak |g| = 0.8669
   against sin(120) = 0.8660: the ring now never reaches further out than the
   back slots already do, so nothing clips and nothing stops. */
@keyframes lg-u3-a-move {
  0.0% { transform: translate(127.935px,143.962px); animation-timing-function: linear; }
  12.5% { transform: translate(104.969px,142.118px); animation-timing-function: linear; }
  25.0% { transform: translate(85.805px,137.326px); animation-timing-function: linear; }
  37.5% { transform: translate(70.591px,130.240px); animation-timing-function: linear; }
  50.0% { transform: translate(64.198px,121.571px); animation-timing-function: linear; }
  62.5% { transform: translate(62.973px,112.103px); animation-timing-function: linear; }
  75.0% { transform: translate(61.750px,102.660px); animation-timing-function: linear; }
  87.5% { transform: translate(60.643px,94.104px); animation-timing-function: linear; }
  100.0% { transform: translate(63.947px,87.952px); }
}
@keyframes lg-u3-b-move {
  0.0% { transform: translate(63.947px,87.952px); animation-timing-function: linear; }
  12.5% { transform: translate(78.460px,78.840px); animation-timing-function: linear; }
  25.0% { transform: translate(96.272px,72.867px); animation-timing-function: linear; }
  37.5% { transform: translate(116.047px,69.764px); animation-timing-function: linear; }
  50.0% { transform: translate(136.184px,69.512px); animation-timing-function: linear; }
  62.5% { transform: translate(155.138px,71.892px); animation-timing-function: linear; }
  75.0% { transform: translate(171.547px,76.445px); animation-timing-function: linear; }
  87.5% { transform: translate(184.306px,82.411px); animation-timing-function: linear; }
  100.0% { transform: translate(192.053px,87.952px); }
}
@keyframes lg-u3-c-move {
  0.0% { transform: translate(192.053px,87.952px); animation-timing-function: linear; }
  12.5% { transform: translate(194.736px,98.901px); animation-timing-function: linear; }
  25.0% { transform: translate(193.343px,109.668px); animation-timing-function: linear; }
  37.5% { transform: translate(192.024px,119.855px); animation-timing-function: linear; }
  50.0% { transform: translate(187.532px,128.777px); animation-timing-function: linear; }
  62.5% { transform: translate(173.970px,135.865px); animation-timing-function: linear; }
  75.0% { transform: translate(157.945px,140.755px); animation-timing-function: linear; }
  87.5% { transform: translate(141.321px,143.345px); animation-timing-function: linear; }
  100.0% { transform: translate(127.935px,143.962px); }
}
@keyframes lg-u3-a-head {
  0.0% { r: 48.000px; animation-timing-function: linear; }
  12.5% { r: 47.737px; animation-timing-function: linear; }
  25.0% { r: 47.052px; animation-timing-function: linear; }
  37.5% { r: 46.040px; animation-timing-function: linear; }
  50.0% { r: 44.802px; animation-timing-function: linear; }
  62.5% { r: 43.450px; animation-timing-function: linear; }
  75.0% { r: 42.101px; animation-timing-function: linear; }
  87.5% { r: 40.879px; animation-timing-function: linear; }
  100.0% { r: 40.000px; }
}
@keyframes lg-u3-c-head {
  0.0% { r: 40.000px; animation-timing-function: linear; }
  12.5% { r: 41.564px; animation-timing-function: linear; }
  25.0% { r: 43.102px; animation-timing-function: linear; }
  37.5% { r: 44.557px; animation-timing-function: linear; }
  50.0% { r: 45.831px; animation-timing-function: linear; }
  62.5% { r: 46.844px; animation-timing-function: linear; }
  75.0% { r: 47.542px; animation-timing-function: linear; }
  87.5% { r: 47.912px; animation-timing-function: linear; }
  100.0% { r: 48.000px; }
}
@keyframes lg-u3-a-body {
  0.0% { d: path("M-29.115,38.108C-43.286,44.203 -55.111,54.702 -62.864,68.038C-64.294,70.513 -64.294,73.563 -62.865,76.039C-61.435,78.514 -58.793,80.039 -55.935,80.038C-18.602,80.038 18.732,80.038 56.065,80.038C58.923,80.039 61.565,78.514 62.995,76.039C64.424,73.563 64.424,70.513 62.995,68.038C55.236,54.712 43.411,44.223 29.255,38.108C9.798,38.108 -9.658,38.108 -29.115,38.108Z"); animation-timing-function: linear; }
  12.5% { d: path("M-29.044,37.827C-43.102,43.875 -54.847,54.271 -62.577,67.476C-63.943,69.95 -63.962,72.983 -62.631,75.442C-61.22,77.954 -58.559,79.513 -55.672,79.512C-18.516,79.512 18.642,79.512 55.798,79.512C58.59,79.394 61.251,77.835 62.757,75.442C64.156,72.967 64.136,69.934 62.703,67.476C54.967,54.28 43.223,43.894 29.179,37.827C9.771,37.827 -9.636,37.827 -29.044,37.827Z"); animation-timing-function: linear; }
  25.0% { d: path("M-28.858,37.095C-42.625,43.02 -54.158,53.149 -61.829,66.014C-63.028,68.484 -63.098,71.474 -62.022,73.888C-60.661,76.498 -57.949,78.146 -54.989,78.144C-18.292,78.144 18.406,78.144 55.103,78.144C57.724,77.716 60.435,76.069 62.136,73.888C63.458,71.417 63.388,68.427 61.945,66.014C54.269,53.157 42.735,43.038 28.982,37.095C9.701,37.095 -9.578,37.095 -28.858,37.095Z"); animation-timing-function: linear; }
  37.5% { d: path("M-28.584,36.014C-41.919,41.757 -53.141,51.49 -60.724,63.852C-61.676,66.317 -61.821,69.242 -61.121,71.59C-59.833,74.346 -57.047,76.123 -53.978,76.121C-17.96,76.121 18.058,76.121 54.076,76.121C56.443,75.235 59.229,73.458 61.22,71.59C62.426,69.124 62.281,66.199 60.823,63.852C53.235,51.497 42.013,41.772 28.69,36.014C9.598,36.014 -9.492,36.014 -28.584,36.014Z"); animation-timing-function: linear; }
  50.0% { d: path("M-28.248,34.69C-41.055,40.212 -51.896,49.46 -59.372,61.207C-60.022,63.666 -60.259,66.513 -60.02,68.779C-58.822,71.712 -55.944,73.649 -52.742,73.646C-17.555,73.646 17.633,73.646 52.82,73.646C54.875,72.2 57.753,70.263 60.098,68.779C61.164,66.319 60.926,63.473 59.45,61.207C51.971,49.466 41.13,40.224 28.332,34.69C9.472,34.69 -9.388,34.69 -28.248,34.69Z"); animation-timing-function: linear; }
  62.5% { d: path("M-27.882,33.245C-40.111,38.524 -50.537,47.243 -57.895,58.318C-58.215,60.771 -58.553,63.531 -58.817,65.71C-57.716,68.835 -54.739,70.947 -51.392,70.943C-17.112,70.943 17.168,70.943 51.448,70.943C53.164,68.885 56.141,66.774 58.873,65.71C59.785,63.256 59.447,60.496 57.951,58.318C50.591,47.247 40.165,38.532 27.942,33.245C9.334,33.245 -9.274,33.245 -27.882,33.245Z"); animation-timing-function: linear; }
  75.0% { d: path("M-27.516,31.803C-39.17,36.84 -49.181,45.032 -56.422,55.436C-56.413,57.882 -56.851,60.557 -57.616,62.648C-56.614,65.966 -53.537,68.252 -50.045,68.247C-16.67,68.247 16.704,68.247 50.079,68.247C51.456,65.579 54.533,63.293 57.65,62.648C58.41,60.201 57.972,57.526 56.456,55.436C49.214,45.035 39.203,36.846 27.553,31.803C9.196,31.803 -9.16,31.803 -27.516,31.803Z"); animation-timing-function: linear; }
  87.5% { d: path("M-27.185,30.497C-38.317,35.315 -47.953,43.029 -55.087,52.826C-54.78,55.266 -55.309,57.863 -56.529,59.873C-55.615,63.367 -52.448,65.81 -48.825,65.805C-16.27,65.805 16.284,65.805 48.839,65.805C49.91,62.584 53.077,60.14 56.543,59.873C57.164,57.433 56.635,54.836 55.101,52.826C47.966,43.03 38.331,35.317 27.201,30.497C9.072,30.497 -9.056,30.497 -27.185,30.497Z"); animation-timing-function: linear; }
  100.0% { d: path("M-26.947,29.558C-37.704,34.218 -47.069,41.588 -54.127,50.948C-53.606,53.384 -54.2,55.925 -55.747,57.878C-54.897,61.497 -51.665,64.054 -47.947,64.048C-15.982,64.048 15.982,64.048 47.947,64.048C48.797,60.429 52.029,57.872 55.747,57.878C56.268,55.442 55.674,52.901 54.127,50.948C47.069,41.588 37.704,34.218 26.947,29.558C8.982,29.558 -8.982,29.558 -26.947,29.558Z"); }
}
@keyframes lg-u3-c-body {
  0.0% { d: path("M-26.947,29.558C-37.704,34.218 -47.069,41.588 -54.127,50.948C-53.606,53.384 -54.2,55.925 -55.747,57.878C-54.897,61.497 -51.665,64.054 -47.947,64.048C-15.982,64.048 15.982,64.048 47.947,64.048C48.797,60.429 52.029,57.872 55.747,57.878C56.268,55.442 55.674,52.901 54.127,50.948C47.069,41.588 37.704,34.218 26.947,29.558C8.982,29.558 -8.982,29.558 -26.947,29.558Z"); animation-timing-function: linear; }
  12.5% { d: path("M-27.371,31.23C-38.795,36.17 -48.641,44.152 -55.835,54.289C-55.696,56.733 -56.174,59.374 -57.139,61.429C-56.175,64.824 -53.059,67.179 -49.509,67.174C-16.494,67.174 16.52,67.174 49.534,67.174C50.777,64.263 53.893,61.908 57.164,61.429C57.863,58.985 57.385,56.345 55.861,54.289C48.666,44.154 38.82,36.174 27.398,31.23C9.142,31.23 -9.114,31.23 -27.371,31.23Z"); animation-timing-function: linear; }
  25.0% { d: path("M-27.788,32.873C-39.868,38.09 -50.187,46.673 -57.515,57.575C-57.75,60.026 -58.114,62.764 -58.507,64.92C-57.432,68.095 -54.429,70.252 -51.044,70.248C-16.998,70.248 17.048,70.248 51.095,70.248C52.723,68.033 55.727,65.876 58.557,64.92C59.43,62.468 59.067,59.73 57.566,57.575C50.236,46.677 39.917,38.097 27.842,32.873C9.298,32.873 -9.244,32.873 -27.788,32.873Z"); animation-timing-function: linear; }
  37.5% { d: path("M-28.182,34.428C-40.884,39.906 -51.65,49.058 -59.104,60.683C-59.694,63.141 -59.95,65.972 -59.802,68.223C-58.621,71.191 -55.725,73.16 -52.497,73.156C-17.474,73.156 17.549,73.156 52.571,73.156C54.565,71.6 57.461,69.63 59.876,68.223C60.914,65.764 60.658,62.933 59.179,60.683C51.721,49.064 40.955,39.917 28.262,34.428C9.447,34.428 -9.367,34.428 -28.182,34.428Z"); animation-timing-function: linear; }
  50.0% { d: path("M-28.527,35.79C-41.773,41.496 -52.931,51.147 -60.496,63.405C-61.397,65.87 -61.558,68.782 -60.935,71.116C-59.663,73.901 -56.861,75.706 -53.77,75.703C-17.892,75.703 17.987,75.703 53.864,75.703C56.178,74.723 58.98,72.918 61.03,71.116C62.213,68.651 62.052,65.739 60.591,63.405C53.022,51.154 41.864,41.511 28.629,35.79C9.577,35.79 -9.475,35.79 -28.527,35.79Z"); animation-timing-function: linear; }
  62.5% { d: path("M-28.802,36.872C-42.479,42.76 -53.949,52.807 -61.601,65.568C-62.749,68.037 -62.835,71.014 -61.836,73.414C-60.49,76.055 -57.763,77.729 -54.781,77.727C-18.223,77.727 18.335,77.727 54.892,77.727C57.46,77.205 60.187,75.531 61.947,73.414C63.245,70.944 63.159,67.968 61.713,65.568C54.056,52.815 42.586,42.777 28.921,36.872C9.68,36.872 -9.56,36.872 -28.802,36.872Z"); animation-timing-function: linear; }
  75.0% { d: path("M-28.991,37.619C-42.967,43.632 -54.651,53.952 -62.364,67.06C-63.682,69.533 -63.716,72.554 -62.458,75C-61.061,77.54 -58.385,79.124 -55.478,79.123C-18.452,79.123 18.575,79.123 55.601,79.123C58.344,78.917 61.019,77.333 62.58,75C63.957,72.526 63.923,69.505 62.488,67.06C54.769,53.961 43.084,43.651 29.123,37.619C9.751,37.619 -9.619,37.619 -28.991,37.619Z"); animation-timing-function: linear; }
  87.5% { d: path("M-29.091,38.014C-43.225,44.093 -55.023,54.558 -62.768,67.85C-64.177,70.325 -64.183,73.369 -62.787,75.839C-61.363,78.327 -58.715,79.863 -55.847,79.862C-18.573,79.862 18.702,79.862 55.976,79.862C58.812,79.824 61.46,78.287 62.915,75.839C64.334,73.364 64.328,70.32 62.898,67.85C55.146,54.568 43.348,44.113 29.23,38.014C9.789,38.014 -9.651,38.014 -29.091,38.014Z"); animation-timing-function: linear; }
  100.0% { d: path("M-29.115,38.108C-43.286,44.203 -55.111,54.702 -62.864,68.038C-64.294,70.513 -64.294,73.563 -62.865,76.039C-61.435,78.514 -58.793,80.039 -55.935,80.038C-18.602,80.038 18.732,80.038 56.065,80.038C58.923,80.039 61.565,78.514 62.995,76.039C64.424,73.563 64.424,70.513 62.995,68.038C55.236,54.712 43.411,44.223 29.255,38.108C9.798,38.108 -9.658,38.108 -29.115,38.108Z"); }
}


/* THE RANK SWAP — and the one number here that is NOT free to choose.

   A and C trade depth when their ring angles satisfy cos(tA) = cos(tC), which
   happens at HALF THE TRAVEL. That is half the EASED progress, not half the
   clock, and the two are only the same moment when the easing is symmetric.

   The first pass used cubic-bezier(0.45,0,0.55,1), which is symmetric, so a gate
   at 50% was correct. Front-loading the curve to fix the
   sluggish start moved half-travel to 19.53% of the clock — and left the gate
   219ms late, so the figure on its way BACK stayed drawn over the one arriving
   in FRONT for a fifth of a second. Bakai spotted it. It is invisible in the
   code and obvious on screen, and it is a coupling worth remembering: THE GATE
   IS TIED TO THE EASING. Re-solve it whenever the curve changes.

   Solve: find m with y(m)=0.5, take x(m). For (0.08,0.12,0.85,0.95) that is 44.84%.
   The swap is still free at that instant — A and C sit at the two BACK slots,
   x63.8 and x192.1, 9.6u apart and unable to touch. */
@keyframes lg-u3-gate-c { 0%,44.83% { visibility: hidden; }  44.84%,100% { visibility: visible; } }
@keyframes lg-u3-gate-a { 0%,44.83% { visibility: visible; } 44.84%,100% { visibility: hidden; } }
`;
