/**
 * LaTeX vocabulary that completion and hover fall back on when TexLab has no
 * answer: common commands with what each means (and the template completion
 * inserts, with the caret in its first empty `{}`), and common environments.
 * Everything a reader sees is a translated descriptor.
 */
import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";

export type VocabularyEntry = { name: string; detail: MessageDescriptor; template?: string; package?: string; math?: boolean };

/** Text commands (`math: false`) and math commands, in the order completion ranks them. */
export const VOCABULARY_COMMANDS: VocabularyEntry[] = [
  { name: "\\section", detail: msg`Top-level section heading`, template: "\\section{}", math: false },
  { name: "\\subsection", detail: msg`Second-level heading`, template: "\\subsection{}", math: false },
  { name: "\\subsubsection", detail: msg`Third-level heading`, template: "\\subsubsection{}", math: false },
  { name: "\\paragraph", detail: msg`Run-in paragraph heading`, template: "\\paragraph{}", math: false },
  { name: "\\label", detail: msg`Cross-reference label`, template: "\\label{}", math: false },
  { name: "\\ref", detail: msg`Reference an existing label`, template: "\\ref{}", math: false },
  { name: "\\eqref", detail: msg`Reference an equation label`, template: "\\eqref{}", math: false },
  { name: "\\citep", detail: msg`Bibliographic citation (requires natbib or compatible package)`, template: "\\citep{}", math: false },
  { name: "\\textbf", detail: msg`Bold text command`, template: "\\textbf{}", math: false },
  { name: "\\emph", detail: msg`Emphasized text command`, template: "\\emph{}", math: false },
  { name: "\\footnote", detail: msg`Footnote at the cursor`, template: "\\footnote{}", math: false },
  { name: "\\includegraphics", detail: msg`Insert an image path (requires graphicx)`, template: "\\includegraphics[width=\\linewidth]{}", math: false },
  { name: "\\input", detail: msg`Inline another TeX file`, template: "\\input{}", math: false },
  { name: "\\include", detail: msg`Include another TeX file`, template: "\\include{}", math: false },
  { name: "\\frac", detail: msg`a over b`, template: "\\frac{}{}", math: true },
  { name: "\\dfrac", detail: msg`Larger fraction`, template: "\\dfrac{}{}", math: true },
  { name: "\\sqrt", detail: msg`Radical`, template: "\\sqrt{}", math: true },
  { name: "\\iint", detail: msg`Surface / area integral`, math: true },
  { name: "\\oint", detail: msg`Closed-path integral`, math: true },
  { name: "\\mathbb", detail: msg`Number sets like R, N`, template: "\\mathbb{}", math: true },
  { name: "\\mathcal", detail: msg`Script letters`, template: "\\mathcal{}", math: true },
  { name: "\\mathrm", detail: msg`Upright text in math`, template: "\\mathrm{}", math: true },
  { name: "\\text", detail: msg`Words inside math mode`, template: "\\text{}", math: true },
  { name: "\\overline", detail: msg`Bar over an expression`, template: "\\overline{}", math: true },
  { name: "\\underline", detail: msg`Line under an expression`, template: "\\underline{}", math: true },
  { name: "\\hat", detail: msg`Estimator / unit vector mark`, template: "\\hat{}", math: true },
  { name: "\\bar", detail: msg`Mean / conjugate mark`, template: "\\bar{}", math: true },
  { name: "\\vec", detail: msg`Vector arrow over a symbol`, template: "\\vec{}", math: true },
  { name: "\\dot", detail: msg`Time derivative mark`, template: "\\dot{}", math: true },
  { name: "\\binom", detail: msg`Binomial coefficient`, template: "\\binom{}{}", math: true },
  { name: "\\alpha", detail: msg`Alpha`, math: true },
  { name: "\\beta", detail: msg`Beta`, math: true },
  { name: "\\gamma", detail: msg`Gamma`, math: true },
  { name: "\\delta", detail: msg`Delta`, math: true },
  { name: "\\epsilon", detail: msg`Epsilon`, math: true },
  { name: "\\varepsilon", detail: msg`Variant epsilon`, math: true },
  { name: "\\zeta", detail: msg`Zeta`, math: true },
  { name: "\\eta", detail: msg`Eta`, math: true },
  { name: "\\theta", detail: msg`Theta`, math: true },
  { name: "\\vartheta", detail: msg`Variant theta`, math: true },
  { name: "\\iota", detail: msg`Iota`, math: true },
  { name: "\\kappa", detail: msg`Kappa`, math: true },
  { name: "\\lambda", detail: msg`Lambda`, math: true },
  { name: "\\mu", detail: msg`Mu`, math: true },
  { name: "\\nu", detail: msg`Nu`, math: true },
  { name: "\\xi", detail: msg`Xi`, math: true },
  { name: "\\pi", detail: msg`Pi`, math: true },
  { name: "\\varpi", detail: msg`Variant pi`, math: true },
  { name: "\\rho", detail: msg`Rho`, math: true },
  { name: "\\varrho", detail: msg`Variant rho`, math: true },
  { name: "\\sigma", detail: msg`Sigma`, math: true },
  { name: "\\varsigma", detail: msg`Final sigma`, math: true },
  { name: "\\tau", detail: msg`Tau`, math: true },
  { name: "\\upsilon", detail: msg`Upsilon`, math: true },
  { name: "\\phi", detail: msg`Phi`, math: true },
  { name: "\\varphi", detail: msg`Variant phi`, math: true },
  { name: "\\chi", detail: msg`Chi`, math: true },
  { name: "\\psi", detail: msg`Psi`, math: true },
  { name: "\\omega", detail: msg`Omega`, math: true },
  { name: "\\Gamma", detail: msg`Capital gamma`, math: true },
  { name: "\\Delta", detail: msg`Capital delta`, math: true },
  { name: "\\Theta", detail: msg`Capital theta`, math: true },
  { name: "\\Lambda", detail: msg`Capital lambda`, math: true },
  { name: "\\Xi", detail: msg`Capital xi`, math: true },
  { name: "\\Pi", detail: msg`Capital pi`, math: true },
  { name: "\\Sigma", detail: msg`Capital sigma`, math: true },
  { name: "\\Upsilon", detail: msg`Capital upsilon`, math: true },
  { name: "\\Phi", detail: msg`Capital phi`, math: true },
  { name: "\\Psi", detail: msg`Capital psi`, math: true },
  { name: "\\Omega", detail: msg`Capital omega`, math: true },
  { name: "\\pm", detail: msg`Plus-minus`, math: true },
  { name: "\\mp", detail: msg`Minus-plus`, math: true },
  { name: "\\times", detail: msg`Times / cross product`, math: true },
  { name: "\\div", detail: msg`Division`, math: true },
  { name: "\\cdot", detail: msg`Centered dot`, math: true },
  { name: "\\ast", detail: msg`Asterisk operator`, math: true },
  { name: "\\star", detail: msg`Star operator`, math: true },
  { name: "\\circ", detail: msg`Composition / ring`, math: true },
  { name: "\\bullet", detail: msg`Bullet`, math: true },
  { name: "\\oplus", detail: msg`Circled plus`, math: true },
  { name: "\\ominus", detail: msg`Circled minus`, math: true },
  { name: "\\otimes", detail: msg`Circled times / tensor`, math: true },
  { name: "\\oslash", detail: msg`Circled slash`, math: true },
  { name: "\\odot", detail: msg`Circled dot`, math: true },
  { name: "\\dagger", detail: msg`Dagger`, math: true },
  { name: "\\ddagger", detail: msg`Double dagger`, math: true },
  { name: "\\amalg", detail: msg`Amalgamation`, math: true },
  { name: "\\cap", detail: msg`Intersection`, math: true },
  { name: "\\cup", detail: msg`Union`, math: true },
  { name: "\\sqcap", detail: msg`Square cap`, math: true },
  { name: "\\sqcup", detail: msg`Square cup`, math: true },
  { name: "\\uplus", detail: msg`Multiset union`, math: true },
  { name: "\\vee", detail: msg`Logical or`, math: true },
  { name: "\\wedge", detail: msg`Logical and`, math: true },
  { name: "\\setminus", detail: msg`Set minus`, math: true },
  { name: "\\wr", detail: msg`Wreath product`, math: true },
  { name: "\\diamond", detail: msg`Diamond operator`, math: true },
  { name: "\\bigtriangleup", detail: msg`Big triangle up`, math: true },
  { name: "\\bigtriangledown", detail: msg`Big triangle down`, math: true },
  { name: "\\triangleleft", detail: msg`Triangle left`, math: true },
  { name: "\\triangleright", detail: msg`Triangle right`, math: true },
  { name: "\\lhd", detail: msg`Left normal subgroup`, math: true },
  { name: "\\rhd", detail: msg`Right normal subgroup`, math: true },
  { name: "\\unlhd", detail: msg`Left normal subgroup eq`, math: true },
  { name: "\\unrhd", detail: msg`Right normal subgroup eq`, math: true },
  { name: "\\leq", detail: msg`Less than or equal`, math: true },
  { name: "\\geq", detail: msg`Greater than or equal`, math: true },
  { name: "\\neq", detail: msg`Not equal`, math: true },
  { name: "\\approx", detail: msg`Approximately equal`, math: true },
  { name: "\\equiv", detail: msg`Equivalent / congruent`, math: true },
  { name: "\\sim", detail: msg`Similar to`, math: true },
  { name: "\\simeq", detail: msg`Similar or equal`, math: true },
  { name: "\\cong", detail: msg`Congruent`, math: true },
  { name: "\\propto", detail: msg`Proportional to`, math: true },
  { name: "\\models", detail: msg`Models / entails`, math: true },
  { name: "\\prec", detail: msg`Precedes`, math: true },
  { name: "\\succ", detail: msg`Succeeds`, math: true },
  { name: "\\preceq", detail: msg`Precedes or equal`, math: true },
  { name: "\\succeq", detail: msg`Succeeds or equal`, math: true },
  { name: "\\subset", detail: msg`Subset`, math: true },
  { name: "\\supset", detail: msg`Superset`, math: true },
  { name: "\\subseteq", detail: msg`Subset or equal`, math: true },
  { name: "\\supseteq", detail: msg`Superset or equal`, math: true },
  { name: "\\sqsubset", detail: msg`Square subset`, math: true },
  { name: "\\sqsupset", detail: msg`Square superset`, math: true },
  { name: "\\sqsubseteq", detail: msg`Square subset eq`, math: true },
  { name: "\\sqsupseteq", detail: msg`Square superset eq`, math: true },
  { name: "\\in", detail: msg`Element of`, math: true },
  { name: "\\ni", detail: msg`Contains as member`, math: true },
  { name: "\\notin", detail: msg`Not an element of`, math: true },
  { name: "\\vdash", detail: msg`Proves / turnstile`, math: true },
  { name: "\\dashv", detail: msg`Reverse turnstile`, math: true },
  { name: "\\smile", detail: msg`Smile relation`, math: true },
  { name: "\\frown", detail: msg`Frown relation`, math: true },
  { name: "\\mid", detail: msg`Divides / conditioned on`, math: true },
  { name: "\\parallel", detail: msg`Parallel`, math: true },
  { name: "\\perp", detail: msg`Perpendicular`, math: true },
  { name: "\\bowtie", detail: msg`Natural join / bowtie`, math: true },
  { name: "\\leftarrow", detail: msg`Left arrow`, math: true },
  { name: "\\rightarrow", detail: msg`Right arrow`, math: true },
  { name: "\\leftrightarrow", detail: msg`Left-right arrow`, math: true },
  { name: "\\Leftarrow", detail: msg`Left double arrow`, math: true },
  { name: "\\Rightarrow", detail: msg`Right double arrow / implies`, math: true },
  { name: "\\Leftrightarrow", detail: msg`Left-right double arrow / iff`, math: true },
  { name: "\\mapsto", detail: msg`Maps to`, math: true },
  { name: "\\hookleftarrow", detail: msg`Hook left arrow`, math: true },
  { name: "\\hookrightarrow", detail: msg`Hook right arrow`, math: true },
  { name: "\\leftharpoonup", detail: msg`Left harpoon up`, math: true },
  { name: "\\rightharpoonup", detail: msg`Right harpoon up`, math: true },
  { name: "\\rightleftharpoons", detail: msg`Equilibrium arrows`, math: true },
  { name: "\\uparrow", detail: msg`Up arrow`, math: true },
  { name: "\\downarrow", detail: msg`Down arrow`, math: true },
  { name: "\\updownarrow", detail: msg`Up-down arrow`, math: true },
  { name: "\\Uparrow", detail: msg`Up double arrow`, math: true },
  { name: "\\Downarrow", detail: msg`Down double arrow`, math: true },
  { name: "\\Updownarrow", detail: msg`Up-down double arrow`, math: true },
  { name: "\\nearrow", detail: msg`North-east arrow`, math: true },
  { name: "\\searrow", detail: msg`South-east arrow`, math: true },
  { name: "\\swarrow", detail: msg`South-west arrow`, math: true },
  { name: "\\nwarrow", detail: msg`North-west arrow`, math: true },
  { name: "\\to", detail: msg`To (short right arrow)`, math: true },
  { name: "\\gets", detail: msg`Gets (short left arrow)`, math: true },
  { name: "\\implies", detail: msg`Implies`, math: true },
  { name: "\\iff", detail: msg`If and only if`, math: true },
  { name: "\\emptyset", detail: msg`Empty set`, math: true },
  { name: "\\varnothing", detail: msg`Empty set (variant)`, math: true },
  { name: "\\langle", detail: msg`Left angle bracket`, math: true },
  { name: "\\rangle", detail: msg`Right angle bracket`, math: true },
  { name: "\\lfloor", detail: msg`Left floor`, math: true },
  { name: "\\rfloor", detail: msg`Right floor`, math: true },
  { name: "\\lceil", detail: msg`Left ceiling`, math: true },
  { name: "\\rceil", detail: msg`Right ceiling`, math: true },
  { name: "\\lvert", detail: msg`Left vertical bar`, math: true },
  { name: "\\rvert", detail: msg`Right vertical bar`, math: true },
  { name: "\\lVert", detail: msg`Left double vertical bar`, math: true },
  { name: "\\rVert", detail: msg`Right double vertical bar`, math: true },
  { name: "\\check", detail: msg`Check accent example`, template: "\\check{}", math: true },
  { name: "\\tilde", detail: msg`Tilde accent example`, template: "\\tilde{}", math: true },
  { name: "\\acute", detail: msg`Acute accent example`, template: "\\acute{}", math: true },
  { name: "\\grave", detail: msg`Grave accent example`, template: "\\grave{}", math: true },
  { name: "\\ddot", detail: msg`Double-dot accent example`, template: "\\ddot{}", math: true },
  { name: "\\breve", detail: msg`Breve accent example`, template: "\\breve{}", math: true },
  { name: "\\infty", detail: msg`Infinity`, math: true },
  { name: "\\nabla", detail: msg`Nabla / del`, math: true },
  { name: "\\partial", detail: msg`Partial derivative`, math: true },
  { name: "\\forall", detail: msg`For all`, math: true },
  { name: "\\exists", detail: msg`There exists`, math: true },
  { name: "\\nexists", detail: msg`Does not exist`, math: true },
  { name: "\\neg", detail: msg`Negation / not`, math: true },
  { name: "\\top", detail: msg`Top / true`, math: true },
  { name: "\\bot", detail: msg`Bottom / false`, math: true },
  { name: "\\angle", detail: msg`Angle`, math: true },
  { name: "\\triangle", detail: msg`Triangle`, math: true },
  { name: "\\square", detail: msg`Square`, math: true },
  { name: "\\blacksquare", detail: msg`Filled square`, math: true },
  { name: "\\diamondsuit", detail: msg`Diamond suit`, math: true },
  { name: "\\heartsuit", detail: msg`Heart suit`, math: true },
  { name: "\\clubsuit", detail: msg`Club suit`, math: true },
  { name: "\\spadesuit", detail: msg`Spade suit`, math: true },
  { name: "\\flat", detail: msg`Flat`, math: true },
  { name: "\\natural", detail: msg`Natural`, math: true },
  { name: "\\sharp", detail: msg`Sharp`, math: true },
  { name: "\\ell", detail: msg`Script l`, math: true },
  { name: "\\hbar", detail: msg`H-bar / reduced Planck`, math: true },
  { name: "\\imath", detail: msg`Dotless i`, math: true },
  { name: "\\jmath", detail: msg`Dotless j`, math: true },
  { name: "\\wp", detail: msg`Weierstrass p`, math: true },
  { name: "\\Re", detail: msg`Real part`, math: true },
  { name: "\\Im", detail: msg`Imaginary part`, math: true },
  { name: "\\aleph", detail: msg`Aleph`, math: true },
  { name: "\\beth", detail: msg`Beth`, math: true },
  { name: "\\gimel", detail: msg`Gimel`, math: true },
  { name: "\\daleth", detail: msg`Daleth`, math: true },
  { name: "\\prime", detail: msg`Prime`, math: true },
  { name: "\\backprime", detail: msg`Back prime`, math: true },
  { name: "\\S", detail: msg`Section sign`, math: true },
  { name: "\\P", detail: msg`Pilcrow / paragraph`, math: true },
  { name: "\\dag", detail: msg`Dagger text symbol`, math: true },
  { name: "\\ddag", detail: msg`Double dagger text symbol`, math: true },
  { name: "\\copyright", detail: msg`Copyright`, math: true },
  { name: "\\pounds", detail: msg`Pounds sterling`, math: true },
];

export const VOCABULARY_ENVIRONMENTS: VocabularyEntry[] = [
  { name: "figure", detail: msg`Floating figure with image, caption, and label (requires graphicx)` },
  { name: "table", detail: msg`Floating table with ruled rows (requires booktabs)` },
  { name: "equation", detail: msg`Numbered single-line equation` },
  // eslint-disable-next-line lingui/no-unlocalized-strings -- a LaTeX environment name
  { name: "equation*", detail: msg`Unnumbered single-line equation` },
  { name: "align", detail: msg`Multi-line aligned equations` },
  // eslint-disable-next-line lingui/no-unlocalized-strings -- a LaTeX environment name
  { name: "align*", detail: msg`Unnumbered aligned equations` },
  { name: "gather", detail: msg`Centered multi-line equations` },
  // eslint-disable-next-line lingui/no-unlocalized-strings -- a LaTeX environment name
  { name: "gather*", detail: msg`Unnumbered centered equations` },
  { name: "subequations", detail: msg`Grouped numbered equations` },
  { name: "bmatrix", detail: msg`Bracketed matrix` },
  { name: "vmatrix", detail: msg`Determinant-style matrix` },
  // eslint-disable-next-line lingui/no-unlocalized-strings -- a LaTeX environment name
  { name: "Bmatrix", detail: msg`Brace-delimited matrix` },
  { name: "multline", detail: msg`Long equation broken across lines` },
  { name: "cases", detail: msg`Piecewise definition` },
  { name: "itemize", detail: msg`Bulleted list` },
  { name: "enumerate", detail: msg`Numbered list` },
  { name: "description", detail: msg`Labeled description list` },
  { name: "quote", detail: msg`Block quotation` },
  { name: "abstract", detail: msg`Abstract environment` },
  { name: "theorem", detail: msg`Theorem block (requires amsthm and a \\newtheorem declaration)` },
  { name: "proof", detail: msg`Proof environment (requires amsthm)` },
  { name: "verbatim", detail: msg`Literal code / text block` },
  { name: "algorithm", detail: msg`Algorithm block (requires algorithm and algpseudocode)` },
  { name: "lstlisting", detail: msg`Syntax-highlighted listing (listings)` },
  { name: "minipage", detail: msg`Side-by-side column block` },
  { name: "center", detail: msg`Centered block` },
  { name: "pmatrix", detail: msg`Parenthesized matrix` },
];
