export const TUTORIAL_STEPS = {
  welcome: 0,
  latex: 1,
  projectFiles: 2,
  presentation: 3,
  viewModes: 4,
  markdown: 5,
  markdownVisual: 6,
  html: 7,
  board: 8,
  spreadsheet: 9,
  spreadsheetTools: 10,
  workspaceActions: 11,
  openPapers: 12,
  papers: 13,
  importVit: 14,
  paperBlog: 15,
  paperFullText: 16,
  paperActions: 17,
  openAgent: 18,
  agent: 19,
} as const;
