export const TUTORIAL_STEPS = {
  welcome: 0,
  latex: 1,
  projectFiles: 2,
  viewModes: 3,
  markdown: 4,
  markdownVisual: 5,
  html: 6,
  board: 7,
  spreadsheet: 8,
  spreadsheetTools: 9,
  presentation: 10,
  workspaceActions: 11,
  openPapers: 12,
  papers: 13,
  importVit: 14,
  paperBlog: 15,
  paperFullText: 16,
  paperActions: 17,
  openAgent: 18,
  agent: 19,
} as const;
