export const TUTORIAL_STEPS = {
  welcome: 0,
  latex: 1,
  projectFiles: 2,
  viewModes: 3,
  markdown: 4,
  markdownVisual: 5,
  html: 6,
  board: 7,
  spreadsheet: 8,
  spreadsheetTools: 9,
  workspaceActions: 10,
  openPapers: 11,
  papers: 12,
  importVit: 13,
  paperBlog: 14,
  paperFullText: 15,
  paperActions: 16,
  openAgent: 17,
  agent: 18,
} as const;
