export type InsertGroup =
  | "Environment"
  | "Structure"
  | "Math"
  | "Greek"
  | "Operators"
  | "Relations"
  | "Arrows"
  | "Sets"
  | "Delimiters"
  | "Accents"
  | "Symbols";

export type InsertSnippet = {
  id: string;
  group: InsertGroup;
  label: string;
  detail: string;
  insert: string;
  cursorOffset?: number;
  /** Visible glyph shown in the palette (Unicode). */
  glyph?: string;
  /** KaTeX source used for the preview tile when glyph is not enough. */
  mathPreview?: string;
  /** Short code preview for environments/snippets. */
  codePreview?: string;
};

function env(
  id: string,
  label: string,
  detail: string,
  insert: string,
  cursorOffset?: number,
): InsertSnippet {
  return {
    id,
    group: "Environment",
    label,
    detail,
    insert,
    cursorOffset,
    codePreview: insert.trim().split("\n").slice(0, 3).join("\n"),
  };
}

function structure(
  id: string,
  label: string,
  detail: string,
  insert: string,
  cursorOffset?: number,
): InsertSnippet {
  return {
    id,
    group: "Structure",
    label,
    detail,
    insert,
    cursorOffset,
    codePreview: insert.trim(),
  };
}

function math(
  id: string,
  label: string,
  detail: string,
  insert: string,
  mathPreview: string,
  cursorOffset?: number,
): InsertSnippet {
  return { id, group: "Math", label, detail, insert, mathPreview, cursorOffset };
}

function greek(command: string, glyph: string, name: string): InsertSnippet {
  return {
    id: `greek-${command.replace("\\", "")}`,
    group: "Greek",
    label: command,
    detail: name,
    insert: command,
    glyph,
    mathPreview: command,
  };
}

function op(command: string, glyph: string, name: string, group: InsertGroup = "Operators"): InsertSnippet {
  return {
    id: `${group.toLowerCase()}-${command.replace(/\\/g, "")}`,
    group,
    label: command,
    detail: name,
    insert: command,
    glyph,
    mathPreview: command,
  };
}

export const INSERT_GROUPS: InsertGroup[] = [
  "Environment",
  "Structure",
  "Math",
  "Greek",
  "Operators",
  "Relations",
  "Arrows",
  "Sets",
  "Delimiters",
  "Accents",
  "Symbols",
];

export const INSERT_SNIPPETS: InsertSnippet[] = [
  env(
    "env-figure",
    "Figure",
    "Floating figure with image, caption, and label",
    "\\begin{figure}[t]\n  \\centering\n  \\includegraphics[width=0.8\\linewidth]{${1:path/to/figure.pdf}}\n  \\caption{${2:Caption}}\n  \\label{${3:fig:name}}\n\\end{figure}\n",
  ),
  env(
    "env-table",
    "Table",
    "Floating table with booktabs-style rows",
    "\\begin{table}[t]\n  \\centering\n  \\caption{${1:Caption}}\n  \\label{${2:tab:name}}\n  \\begin{tabular}{lcc}\n    \\toprule\n    Method & Score & Notes \\\\\n    \\midrule\n    Ours & 90 &  \\\\\n    \\bottomrule\n  \\end{tabular}\n\\end{table}\n",
  ),
  env(
    "env-equation",
    "Equation",
    "Numbered single-line equation",
    "\\begin{equation}\n  ${1:}\n  \\label{${2:eq:name}}\n\\end{equation}\n",
  ),
  env(
    "env-equation-star",
    "Equation*",
    "Unnumbered single-line equation",
    "\\begin{equation*}\n  ${1:}\n\\end{equation*}\n",
  ),
  env(
    "env-align",
    "Align",
    "Multi-line aligned equations",
    "\\begin{align}\n  a &= b \\\\\n  c &= d\n\\end{align}\n",
    14,
  ),
  env(
    "env-align-star",
    "Align*",
    "Unnumbered aligned equations",
    "\\begin{align*}\n  a &= b \\\\\n  c &= d\n\\end{align*}\n",
    15,
  ),
  env(
    "env-gather",
    "Gather",
    "Centered multi-line equations",
    "\\begin{gather}\n  a = b \\\\\n  c = d\n\\end{gather}\n",
    15,
  ),
  env(
    "env-gather-star",
    "Gather*",
    "Unnumbered centered equations",
    "\\begin{gather*}\n  a = b \\\\\n  c = d\n\\end{gather*}\n",
    16,
  ),
  env(
    "env-subequations",
    "Subequations",
    "Grouped numbered equations",
    "\\begin{subequations}\n  \\begin{align}\n    a &= b \\\\\n    c &= d\n  \\end{align}\n\\end{subequations}\n",
    36,
  ),
  env(
    "env-bmatrix",
    "Bmatrix",
    "Bracketed matrix",
    "\\begin{bmatrix}\n  a & b \\\\\n  c & d\n\\end{bmatrix}",
    18,
  ),
  env(
    "env-vmatrix",
    "Vmatrix",
    "Determinant-style matrix",
    "\\begin{vmatrix}\n  a & b \\\\\n  c & d\n\\end{vmatrix}",
    18,
  ),
  env(
    "env-Bmatrix",
    "Curly matrix",
    "Brace-delimited matrix",
    "\\begin{Bmatrix}\n  a & b \\\\\n  c & d\n\\end{Bmatrix}",
    18,
  ),
  env(
    "env-multline",
    "Multline",
    "Long equation broken across lines",
    "\\begin{multline}\n  a + b + c \\\\\n  + d + e\n\\end{multline}\n",
    17,
  ),
  env(
    "env-cases",
    "Cases",
    "Piecewise definition",
    "\\begin{cases}\n  a & \\text{if } x > 0 \\\\\n  b & \\text{otherwise}\n\\end{cases}",
    14,
  ),
  env(
    "env-itemize",
    "Itemize",
    "Bulleted list",
    "\\begin{itemize}\n  \\item \n\\end{itemize}\n",
    22,
  ),
  env(
    "env-enumerate",
    "Enumerate",
    "Numbered list",
    "\\begin{enumerate}\n  \\item \n\\end{enumerate}\n",
    24,
  ),
  env(
    "env-description",
    "Description",
    "Labeled description list",
    "\\begin{description}\n  \\item[Term] Definition\n\\end{description}\n",
    28,
  ),
  env(
    "env-quote",
    "Quote",
    "Block quotation",
    "\\begin{quote}\n  \n\\end{quote}\n",
    14,
  ),
  env(
    "env-abstract",
    "Abstract",
    "Abstract environment",
    "\\begin{abstract}\n  \n\\end{abstract}\n",
    17,
  ),
  env(
    "env-theorem",
    "Theorem",
    "Theorem block (requires amsthm)",
    "\\begin{theorem}\n  \n\\end{theorem}\n",
    16,
  ),
  env(
    "env-proof",
    "Proof",
    "Proof environment",
    "\\begin{proof}\n  \n\\end{proof}\n",
    14,
  ),
  env(
    "env-verbatim",
    "Verbatim",
    "Literal code / text block",
    "\\begin{verbatim}\n\n\\end{verbatim}\n",
    17,
  ),
  env(
    "env-algorithm",
    "Algorithm",
    "Algorithm block (algorithm2e / algorithmicx style)",
    "\\begin{algorithm}\n  \\caption{Caption}\n  \\label{alg:name}\n  \\begin{algorithmic}[1]\n    \\State \n  \\end{algorithmic}\n\\end{algorithm}\n",
    95,
  ),
  env(
    "env-lstlisting",
    "Code listing",
    "Syntax-highlighted listing (listings)",
    "\\begin{lstlisting}[language=Python]\n\n\\end{lstlisting}\n",
    36,
  ),
  env(
    "env-minipage",
    "Minipage",
    "Side-by-side column block",
    "\\begin{minipage}{0.48\\linewidth}\n  \n\\end{minipage}\n",
    36,
  ),
  env(
    "env-center",
    "Center",
    "Centered block",
    "\\begin{center}\n  \n\\end{center}\n",
    15,
  ),

  structure("sec-section", "Section", "Top-level section heading", "\\section{}\n", 9),
  structure("sec-subsection", "Subsection", "Second-level heading", "\\subsection{}\n", 12),
  structure("sec-subsubsection", "Subsubsection", "Third-level heading", "\\subsubsection{}\n", 15),
  structure("sec-paragraph", "Paragraph", "Run-in paragraph heading", "\\paragraph{}\n", 11),
  structure("sec-label", "Label", "Cross-reference label", "\\label{}", 7),
  structure("sec-ref", "Reference", "Reference an existing label", "\\ref{}", 5),
  structure("sec-eqref", "Equation reference", "Reference an equation label", "\\eqref{}", 7),
  structure("sec-cite", "Citation", "Bibliographic citation", "\\citep{}", 6),
  structure("sec-textbf", "Bold", "Bold text command", "\\textbf{}", 8),
  structure("sec-emph", "Emphasis", "Emphasized text command", "\\emph{}", 6),
  structure("sec-footnote", "Footnote", "Footnote at the cursor", "\\footnote{}", 10),
  structure("sec-includegraphics", "Include graphics", "Insert an image path", "\\includegraphics[width=\\linewidth]{}", 34),
  structure("sec-input", "Input file", "Inline another TeX file", "\\input{}", 7),
  structure("sec-include", "Include file", "Include another TeX file", "\\include{}", 9),

  math("math-inline", "Inline math", "Math inside a sentence", "$ $", "x", 1),
  math("math-display", "Display math", "Centered display equation", "\\[\n  \n\\]\n", "x^{2}", 4),
  math("math-frac", "Fraction", "a over b", "\\frac{}{}", "\\frac{a}{b}", 6),
  math("math-dfrac", "Display fraction", "Larger fraction", "\\dfrac{}{}", "\\dfrac{a}{b}", 7),
  math("math-sqrt", "Square root", "Radical", "\\sqrt{}", "\\sqrt{x}", 6),
  math("math-sqrtn", "Nth root", "Root with index", "\\sqrt[]{}", "\\sqrt[n]{x}", 6),
  math("math-sum", "Summation", "Sum with limits", "\\sum_{i=1}^{n} ", "\\sum_{i=1}^{n}", 15),
  math("math-prod", "Product", "Product with limits", "\\prod_{i=1}^{n} ", "\\prod_{i=1}^{n}", 16),
  math("math-int", "Integral", "Integral with limits", "\\int_{a}^{b} ", "\\int_{a}^{b}", 13),
  math("math-iint", "Double integral", "Surface / area integral", "\\iint ", "\\iint", 6),
  math("math-oint", "Contour integral", "Closed-path integral", "\\oint ", "\\oint", 6),
  math("math-lim", "Limit", "Limit expression", "\\lim_{n \\to \\infty} ", "\\lim_{n \\to \\infty}", 20),
  math("math-max", "Max", "Maximum operator", "\\max_{x} ", "\\max_{x}", 8),
  math("math-min", "Min", "Minimum operator", "\\min_{x} ", "\\min_{x}", 8),
  math("math-mathbb", "Blackboard bold", "Number sets like R, N", "\\mathbb{}", "\\mathbb{R}", 8),
  math("math-mathcal", "Calligraphic", "Script letters", "\\mathcal{}", "\\mathcal{L}", 9),
  math("math-mathrm", "Roman math", "Upright text in math", "\\mathrm{}", "\\mathrm{d}x", 8),
  math("math-text", "Text in math", "Words inside math mode", "\\text{}", "\\text{if}", 6),
  math("math-overline", "Overline", "Bar over an expression", "\\overline{}", "\\overline{x}", 10),
  math("math-underline", "Underline", "Line under an expression", "\\underline{}", "\\underline{x}", 11),
  math("math-hat", "Hat accent", "Estimator / unit vector mark", "\\hat{}", "\\hat{x}", 5),
  math("math-bar", "Bar accent", "Mean / conjugate mark", "\\bar{}", "\\bar{x}", 5),
  math("math-vec", "Vector accent", "Vector arrow over a symbol", "\\vec{}", "\\vec{x}", 5),
  math("math-dot", "Dot accent", "Time derivative mark", "\\dot{}", "\\dot{x}", 5),
  math("math-binom", "Binomial", "Binomial coefficient", "\\binom{}{}", "\\binom{n}{k}", 7),
  math("math-matrix", "Matrix", "Parenthesized matrix", "\\begin{pmatrix}\n  a & b \\\\\n  c & d\n\\end{pmatrix}", "\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}", 18),

  ...[
    ["\\alpha", "α", "Alpha"],
    ["\\beta", "β", "Beta"],
    ["\\gamma", "γ", "Gamma"],
    ["\\delta", "δ", "Delta"],
    ["\\epsilon", "ϵ", "Epsilon"],
    ["\\varepsilon", "ε", "Variant epsilon"],
    ["\\zeta", "ζ", "Zeta"],
    ["\\eta", "η", "Eta"],
    ["\\theta", "θ", "Theta"],
    ["\\vartheta", "ϑ", "Variant theta"],
    ["\\iota", "ι", "Iota"],
    ["\\kappa", "κ", "Kappa"],
    ["\\lambda", "λ", "Lambda"],
    ["\\mu", "μ", "Mu"],
    ["\\nu", "ν", "Nu"],
    ["\\xi", "ξ", "Xi"],
    ["\\pi", "π", "Pi"],
    ["\\varpi", "ϖ", "Variant pi"],
    ["\\rho", "ρ", "Rho"],
    ["\\varrho", "ϱ", "Variant rho"],
    ["\\sigma", "σ", "Sigma"],
    ["\\varsigma", "ς", "Final sigma"],
    ["\\tau", "τ", "Tau"],
    ["\\upsilon", "υ", "Upsilon"],
    ["\\phi", "ϕ", "Phi"],
    ["\\varphi", "φ", "Variant phi"],
    ["\\chi", "χ", "Chi"],
    ["\\psi", "ψ", "Psi"],
    ["\\omega", "ω", "Omega"],
    ["\\Gamma", "Γ", "Capital gamma"],
    ["\\Delta", "Δ", "Capital delta"],
    ["\\Theta", "Θ", "Capital theta"],
    ["\\Lambda", "Λ", "Capital lambda"],
    ["\\Xi", "Ξ", "Capital xi"],
    ["\\Pi", "Π", "Capital pi"],
    ["\\Sigma", "Σ", "Capital sigma"],
    ["\\Upsilon", "Υ", "Capital upsilon"],
    ["\\Phi", "Φ", "Capital phi"],
    ["\\Psi", "Ψ", "Capital psi"],
    ["\\Omega", "Ω", "Capital omega"],
  ].map(([command, glyph, name]) => greek(command, glyph, name)),

  ...[
    ["\\pm", "±", "Plus-minus"],
    ["\\mp", "∓", "Minus-plus"],
    ["\\times", "×", "Times / cross product"],
    ["\\div", "÷", "Division"],
    ["\\cdot", "·", "Centered dot"],
    ["\\ast", "∗", "Asterisk operator"],
    ["\\star", "⋆", "Star operator"],
    ["\\circ", "∘", "Composition / ring"],
    ["\\bullet", "•", "Bullet"],
    ["\\oplus", "⊕", "Circled plus"],
    ["\\ominus", "⊖", "Circled minus"],
    ["\\otimes", "⊗", "Circled times / tensor"],
    ["\\oslash", "⊘", "Circled slash"],
    ["\\odot", "⊙", "Circled dot"],
    ["\\dagger", "†", "Dagger"],
    ["\\ddagger", "‡", "Double dagger"],
    ["\\amalg", "⨿", "Amalgamation"],
    ["\\cap", "∩", "Intersection"],
    ["\\cup", "∪", "Union"],
    ["\\sqcap", "⊓", "Square cap"],
    ["\\sqcup", "⊔", "Square cup"],
    ["\\uplus", "⊎", "Multiset union"],
    ["\\vee", "∨", "Logical or"],
    ["\\wedge", "∧", "Logical and"],
    ["\\setminus", "∖", "Set minus"],
    ["\\wr", "≀", "Wreath product"],
    ["\\diamond", "⋄", "Diamond operator"],
    ["\\bigtriangleup", "△", "Big triangle up"],
    ["\\bigtriangledown", "▽", "Big triangle down"],
    ["\\triangleleft", "◁", "Triangle left"],
    ["\\triangleright", "▷", "Triangle right"],
    ["\\lhd", "⊲", "Left normal subgroup"],
    ["\\rhd", "⊳", "Right normal subgroup"],
    ["\\unlhd", "⊴", "Left normal subgroup eq"],
    ["\\unrhd", "⊵", "Right normal subgroup eq"],
  ].map(([command, glyph, name]) => op(command, glyph, name, "Operators")),

  ...[
    ["\\leq", "≤", "Less than or equal"],
    ["\\geq", "≥", "Greater than or equal"],
    ["\\neq", "≠", "Not equal"],
    ["\\approx", "≈", "Approximately equal"],
    ["\\equiv", "≡", "Equivalent / congruent"],
    ["\\sim", "∼", "Similar to"],
    ["\\simeq", "≃", "Similar or equal"],
    ["\\cong", "≅", "Congruent"],
    ["\\propto", "∝", "Proportional to"],
    ["\\models", "⊨", "Models / entails"],
    ["\\prec", "≺", "Precedes"],
    ["\\succ", "≻", "Succeeds"],
    ["\\preceq", "⪯", "Precedes or equal"],
    ["\\succeq", "⪰", "Succeeds or equal"],
    ["\\subset", "⊂", "Subset"],
    ["\\supset", "⊃", "Superset"],
    ["\\subseteq", "⊆", "Subset or equal"],
    ["\\supseteq", "⊇", "Superset or equal"],
    ["\\sqsubset", "⊏", "Square subset"],
    ["\\sqsupset", "⊐", "Square superset"],
    ["\\sqsubseteq", "⊑", "Square subset eq"],
    ["\\sqsupseteq", "⊒", "Square superset eq"],
    ["\\in", "∈", "Element of"],
    ["\\ni", "∋", "Contains as member"],
    ["\\notin", "∉", "Not an element of"],
    ["\\vdash", "⊢", "Proves / turnstile"],
    ["\\dashv", "⊣", "Reverse turnstile"],
    ["\\smile", "⌣", "Smile relation"],
    ["\\frown", "⌢", "Frown relation"],
    ["\\mid", "∣", "Divides / conditioned on"],
    ["\\parallel", "∥", "Parallel"],
    ["\\perp", "⊥", "Perpendicular"],
    ["\\bowtie", "⋈", "Natural join / bowtie"],
  ].map(([command, glyph, name]) => op(command, glyph, name, "Relations")),

  ...[
    ["\\leftarrow", "←", "Left arrow"],
    ["\\rightarrow", "→", "Right arrow"],
    ["\\leftrightarrow", "↔", "Left-right arrow"],
    ["\\Leftarrow", "⇐", "Left double arrow"],
    ["\\Rightarrow", "⇒", "Right double arrow / implies"],
    ["\\Leftrightarrow", "⇔", "Left-right double arrow / iff"],
    ["\\mapsto", "↦", "Maps to"],
    ["\\hookleftarrow", "↩", "Hook left arrow"],
    ["\\hookrightarrow", "↪", "Hook right arrow"],
    ["\\leftharpoonup", "↼", "Left harpoon up"],
    ["\\rightharpoonup", "⇀", "Right harpoon up"],
    ["\\rightleftharpoons", "⇌", "Equilibrium arrows"],
    ["\\uparrow", "↑", "Up arrow"],
    ["\\downarrow", "↓", "Down arrow"],
    ["\\updownarrow", "↕", "Up-down arrow"],
    ["\\Uparrow", "⇑", "Up double arrow"],
    ["\\Downarrow", "⇓", "Down double arrow"],
    ["\\Updownarrow", "⇕", "Up-down double arrow"],
    ["\\nearrow", "↗", "North-east arrow"],
    ["\\searrow", "↘", "South-east arrow"],
    ["\\swarrow", "↙", "South-west arrow"],
    ["\\nwarrow", "↖", "North-west arrow"],
    ["\\to", "→", "To (short right arrow)"],
    ["\\gets", "←", "Gets (short left arrow)"],
    ["\\implies", "⟹", "Implies"],
    ["\\iff", "⟺", "If and only if"],
  ].map(([command, glyph, name]) => op(command, glyph, name, "Arrows")),

  ...[
    ["\\emptyset", "∅", "Empty set"],
    ["\\varnothing", "∅", "Empty set (variant)"],
    ["\\infty", "∞", "Infinity"],
    ["\\nabla", "∇", "Nabla / del"],
    ["\\partial", "∂", "Partial derivative"],
    ["\\forall", "∀", "For all"],
    ["\\exists", "∃", "There exists"],
    ["\\nexists", "∄", "Does not exist"],
    ["\\neg", "¬", "Negation / not"],
    ["\\top", "⊤", "Top / true"],
    ["\\bot", "⊥", "Bottom / false"],
    ["\\angle", "∠", "Angle"],
    ["\\triangle", "△", "Triangle"],
    ["\\square", "□", "Square"],
    ["\\blacksquare", "■", "Filled square"],
    ["\\diamondsuit", "♢", "Diamond suit"],
    ["\\heartsuit", "♡", "Heart suit"],
    ["\\clubsuit", "♣", "Club suit"],
    ["\\spadesuit", "♠", "Spade suit"],
    ["\\flat", "♭", "Flat"],
    ["\\natural", "♮", "Natural"],
    ["\\sharp", "♯", "Sharp"],
  ].map(([command, glyph, name]) => op(command, glyph, name, "Sets")),

  ...[
    ["\\langle", "⟨", "Left angle bracket"],
    ["\\rangle", "⟩", "Right angle bracket"],
    ["\\lfloor", "⌊", "Left floor"],
    ["\\rfloor", "⌋", "Right floor"],
    ["\\lceil", "⌈", "Left ceiling"],
    ["\\rceil", "⌉", "Right ceiling"],
    ["\\lvert", "|", "Left vertical bar"],
    ["\\rvert", "|", "Right vertical bar"],
    ["\\lVert", "‖", "Left double vertical bar"],
    ["\\rVert", "‖", "Right double vertical bar"],
    ["\\{", "{", "Left brace"],
    ["\\}", "}", "Right brace"],
  ].map(([command, glyph, name]) => op(command, glyph, name, "Delimiters")),

  ...[
    ["\\hat{a}", "â", "Hat accent example", "\\hat{}"],
    ["\\check{a}", "ǎ", "Check accent example", "\\check{}"],
    ["\\tilde{a}", "ã", "Tilde accent example", "\\tilde{}"],
    ["\\acute{a}", "á", "Acute accent example", "\\acute{}"],
    ["\\grave{a}", "à", "Grave accent example", "\\grave{}"],
    ["\\dot{a}", "ȧ", "Dot accent example", "\\dot{}"],
    ["\\ddot{a}", "ä", "Double-dot accent example", "\\ddot{}"],
    ["\\breve{a}", "ă", "Breve accent example", "\\breve{}"],
    ["\\bar{a}", "ā", "Bar accent example", "\\bar{}"],
    ["\\vec{a}", "a⃗", "Vector accent example", "\\vec{}"],
  ].map(([preview, glyph, name, insert], index) => ({
    id: `accent-${index}`,
    group: "Accents" as const,
    label: insert,
    detail: name,
    insert: `${insert}`,
    cursorOffset: insert.length - 1,
    glyph,
    mathPreview: preview,
  })),

  ...[
    ["\\ell", "ℓ", "Script l"],
    ["\\hbar", "ℏ", "H-bar / reduced Planck"],
    ["\\imath", "ı", "Dotless i"],
    ["\\jmath", "ȷ", "Dotless j"],
    ["\\wp", "℘", "Weierstrass p"],
    ["\\Re", "ℜ", "Real part"],
    ["\\Im", "ℑ", "Imaginary part"],
    ["\\aleph", "ℵ", "Aleph"],
    ["\\beth", "ℶ", "Beth"],
    ["\\gimel", "ℷ", "Gimel"],
    ["\\daleth", "ℸ", "Daleth"],
    ["\\prime", "′", "Prime"],
    ["\\backprime", "‵", "Back prime"],
    ["\\degree", "°", "Degree"],
    ["\\% ", "%", "Percent"],
    ["\\&", "&", "Ampersand"],
    ["\\_", "_", "Underscore"],
    ["\\S", "§", "Section sign"],
    ["\\P", "¶", "Pilcrow / paragraph"],
    ["\\dag", "†", "Dagger text symbol"],
    ["\\ddag", "‡", "Double dagger text symbol"],
    ["\\copyright", "©", "Copyright"],
    ["\\pounds", "£", "Pounds sterling"],
  ].map(([command, glyph, name]) => op(command.trimEnd(), glyph, name, "Symbols")),
];
