export const TUTORIAL_STEPS = {
  welcome: 0,
  latex: 1,
  projectFiles: 2,
  viewModes: 3,
  markdown: 4,
  markdownVisual: 5,
  html: 6,
  board: 7,
  collaboration: 8,
  collaborationPanel: 9,
  overleaf: 10,
  overleafPanel: 11,
  git: 12,
  gitPanel: 13,
  openPapers: 14,
  papers: 15,
  importVit: 16,
  paperBlog: 17,
  paperFullText: 18,
  openAgent: 19,
  agent: 20,
} as const;
