export const TUTORIAL_STEPS = {
  welcome: 0,
  latex: 1,
  projectFiles: 2,
  viewModes: 3,
  markdown: 4,
  markdownVisual: 5,
  html: 6,
  board: 7,
  workspaceActions: 8,
  openPapers: 9,
  papers: 10,
  importVit: 11,
  paperBlog: 12,
  paperFullText: 13,
  openAgent: 14,
  agent: 15,
} as const;
